### ISSUE TITLE
Embedded python not found. Please install manually.

### ISSUE THREAD

**Issue by MichaMaGit** [Gourieff/comfyui-reactor-node#10]
Hi,
I am getting this error: Embedded python not found. Please install manually.
I am using the git clone ComfyUI version. Not the ComfyUI Portable.

thx

**Comment by Gourieff** [comment]
Hello!
If you don't have the `python_embeded` folder inside, so you might have `venv` folder - right?
Or what folder structure do you have there?

**Comment by MichaMaGit** [comment]
That's the weird part, none of them.
![1](https://github.com/Gourieff/comfyui-reactor-node/assets/122025139/f57ffd08-d065-4aae-88ed-e1955d2e3100)

**Comment by Gourieff** [comment]
It won't work without a proper python's enclosure, e.g. Venv, Conda or Embedded variant
You need this version to make it run in Windows: https://github.com/comfyanonymous/ComfyUI/releases/download/latest/ComfyUI_windows_portable_nvidia_cu118_or_cpu.7z
For details please read https://github.com/comfyanonymous/ComfyUI#installing

**Comment by MichaMaGit** [comment]
thx a lot, I will check it out
