### ISSUE TITLE
[SOLVED] When using 1k3d68.onnx: Landmark.get() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by ttulttul** [Gourieff/comfyui-reactor-node#102]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

When using the 1k3d68.onnx model (SHA256 verified correct), I get a weird positional arguments error that makes no sense. Three arguments are clearly being passed to the function, but Python complains that four were provided. This error does not occur with the inswapper_128.onnx model.

### Steps to reproduce the problem

<img width="297" alt="image" src="https://github.com/Gourieff/comfyui-reactor-node/assets/852933/edc64d60-5287-4263-995d-5d6c4a5a0eab">

### Sysinfo

Running in a container on Vast.ai.

### Relevant console log

```Shell
:35:25 - ReActor Node - STATUS - Working: source face index [0], target face index [0]
16:35:25 - ReActor Node - STATUS - Using Ready Source Face(s) Model...
16:35:25 - ReActor Node - STATUS - Analyzing Target Image...
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/workspace/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/workspace/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/workspace/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 91, in execute
    script.process(
  File "/workspace/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_faceswap.py", line 93, in process
    result = swap_face(
  File "/workspace/ComfyUI/custom_nodes/comfyui-reactor-node/scripts/reactor_swapper.py", line 235, in swap_face
    result = face_swapper.get(result, target_face, source_face)
TypeError: Landmark.get() takes 3 positional arguments but 4 were given
```

### Additional information

I verified that the arguments being passed to Landmark.get() are:

`<class 'numpy.ndarray'>, <class 'insightface.app.common.Face'>, <class 'insightface.app.common.Face'>`

**Comment by Gourieff** [comment]
This is very strange that you have `1k3d68.onnx` in the list
It should be inside `models\insightface\models\buffalo_l` but not in `models\insightface`
`1k3d68.onnx` is the alignment model - not the inswapper type

**Comment by ttulttul** [comment]
> This is very strange that you have `1k3d68.onnx` in the list It should be inside `models\insightface\models\buffalo_l` but not in `models\insightface` `1k3d68.onnx` is the alignment model - not the inswapper type

Thanks very much! I have no idea how it got into the wrong folder... will fix.
