### ISSUE TITLE
Doesnt Work without Face Model

### ISSUE THREAD

**Issue by haquannes** [Gourieff/comfyui-reactor-node#105]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I get error if I run it without face model

### Steps to reproduce the problem

Your workflow
i run reactor with no facemodel, I get error, then I run it with one facemodel, and delete the loadfacemodel node, this time it works. 

### Sysinfo

Windows, python 3.10.9
Total VRAM 8192 MB, total RAM 130971 MB
xformers version: 0.0.22.post4+cu118
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention

### Relevant console log

```Shell
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "c:\AI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "c:\AI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "c:\AI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\AI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 133, in execute
    face_model_to_provide = get_current_faces_model()[0]
IndexError: list index out of range
```

**Comment by Gourieff** [comment]
If you got this error only once - it can be caused by an old state of the node in the workflow
I've just test it once again - everything works pretty fine in different states

**Comment by haquannes** [comment]
today it works, I must have done something wrong, thanks

**Comment by Gourieff** [comment]
> today it works, I must have done something wrong, thanks

There was an error after all
Fixed https://github.com/Gourieff/comfyui-reactor-node/commit/3a6304699312e9f42b4b443a8529c28a90309e39
