### ISSUE TITLE
How to install in Linux?

### ISSUE THREAD

**Issue by yunwuhai** [Gourieff/comfyui-reactor-node#107]
### Feature description

I did not see any introduction to installing Reactors in Linux in README, and I also inquired about the relevant content in [Discussion](https://github.com/Gourieff/comfyui-reactor-node/discussions/85#discussion-5796423), but no one answered. Therefore, I initiated this issue to know if there is currently support for Linux installation, or if there are any ways to install Reactors in Linux? If there is a method, I hope to add an introduction to README.

**Comment by Gourieff** [comment]
ReActor (as itself) works at any platform (via ComfyUI or SD WebUI), it doesn't depend Windows you have or Linux or Mac OS
You just need to install ComfyUI, there are a lot of instructions how to do it in Linux
e.g. https://easywithai.com/guide/how-to-install-comfyui/
And then install ReActor via ComfyUI Manager (the simplest way) or clone it into the `ComfyUI/custom_nodes` folder and run `install.py`

**Comment by scottonanski** [comment]
> ReActor (as itself) works at any platform (via ComfyUI or SD WebUI), it doesn't depend Windows you have or Linux or Mac OS You just need to install ComfyUI, there are a lot of instructions how to do it in Linux e.g. https://easywithai.com/guide/how-to-install-comfyui/ And then install ReActor via ComfyUI Manager (the simplest way) or clone it into the `ComfyUI/custom_nodes` folder and run `install.py`


When installing, this is the only message that get's bounced back;

![image](https://github.com/Gourieff/comfyui-reactor-node/assets/110937649/557c5c3d-499c-4635-a3a6-3024e2ddfd1b)


And in ComfyUI, the models aren't installed;

![image](https://github.com/Gourieff/comfyui-reactor-node/assets/110937649/0eb0679f-a769-4f3a-aa67-9f2e83266a35)

Can you elaborate, preferably with details, on how to rectify this issue?

Thanks.
