### ISSUE TITLE
Error list index out of range in Comfy

### ISSUE THREAD

**Issue by epicstar7** [Gourieff/comfyui-reactor-node#108]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Never had any issues swapping faces with the node in Comfyui but now suddenly with some images (others apparently not) i get this error when using the node.

### Steps to reproduce the problem

Swap a face in Comfyui

### Sysinfo

Windows 11 RTXA4500 Firefox

### Relevant console log

```Shell
Error occurred when executing ReActorFaceSwap:

list index out of range

  File "C:\df\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\df\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\df\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\df\stable-diffusion-webui\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 133, in execute
    face_model_to_provide = get_current_faces_model()[0]
```

### Additional information

It worked before so potentially after some updates something is broken inside the node (or other nodes?).

**Comment by YureP** [comment]
The same for me. 
I tried to solve clearing the cache of the browser (vivaldi), using another browser (opera), a fresh install of Comfyui + custom nodes both in a Python 3.11 and 3.10 conda environment, creating new workflows with the face swap node from scratch, and so on, but the error returns. Usually, after a new installation of the node, the workflow goes well until I change one of the images (source or input). After that, i get always the "index out of range error" every time I use the last faceswap node.
Reverting to the previous version, all workflow run without errors.

**Comment by Gourieff** [comment]
Fixed https://github.com/Gourieff/comfyui-reactor-node/commit/3a6304699312e9f42b4b443a8529c28a90309e39

**Comment by YureP** [comment]
Great!

**Comment by GiacomoFergnani** [comment]
> Great!

How did you solve it?

**Comment by nicolasluethy** [comment]
How did you solve it? facing the same issue currently.. @Gourieff

**Comment by Buumcode** [comment]
[SOLVED] manually
Got this error, when trying to do Batch Face Swap on BMP images (file extesion is 'bmp' – image001.bmp)
---Console log:---
got prompt
!!! Exception during processing !!! list index out of range
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 168, in _map_node_over_list
    input_dict = slice_dict(input_data_all, i)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 144, in slice_dict
    return {k: v[i if len(v) > i else -1] for k, v in d.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 144, in <dictcomp>
    return {k: v[i if len(v) > i else -1] for k, v in d.items()}
               ~^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
------
SOLVED  with rename extension from BMP to JPEG.
