### ISSUE TITLE
[SOLVED] ReActor stops ControlNet from working.

### ISSUE THREAD

**Issue by sturentz** [Gourieff/comfyui-reactor-node#112]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Using portable Windows. The only way I get Reactor to work is via this:
https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

Tried install manager, but that doesn't work, only by following the steps in the above link. However, doing so stops ControlNet from working (preprocessors) the error is that Control Net couldn't load. 

I've tried loading Reactor First and then ControlNet
ControlNet and then Reactor

Reactor wins either way but ControlNet loses the battle. Help please.

### Steps to reproduce the problem

Your workflow
1. Download latest Windows Portable
2. Load Manager
3. Load Reactor via Manager
4. Following additional steps to get Reactor to Work https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild
5. Load ControlNet via Manager

Flipping the steps, where #5 happens then 3 and 4 will at first have ControlNet working (preprocessors) but then step #4 will break controlnet

### Sysinfo

Windows 11, RTX 2060

### Relevant console log

```Shell
No issues with ControlNet Auxiliary Preprocessorsuntil Reactor added. Or... no issues with Reactor until adding ComfyUI's ControlNet Auxiliary Preprocessors

Total VRAM 6144 MB, total RAM 32698 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
Adding extra search path checkpoints D:/ai3/models/Stable-diffusion
Adding extra search path configs D:/ai3/models/Stable-diffusion
Adding extra search path vae D:/ai3/models/VAE
Adding extra search path loras D:/ai3/models/Lora
Adding extra search path loras D:/ai3/models/LyCORIS
Adding extra search path upscale_models D:/ai3/models/ESRGAN
Adding extra search path upscale_models D:/ai3/models/RealESRGAN
Adding extra search path upscale_models D:/ai3/models/SwinIR
Adding extra search path embeddings D:/ai3/embeddings
Adding extra search path hypernetworks D:/ai3/models/hypernetworks
Adding extra search path controlnet D:/ai3/models/ControlNet
### Loading: ComfyUI-Manager (V1.4.1)
### ComfyUI Revision: 1612 [2ec6158e] | Released on '2023-10-22'
Total VRAM 6144 MB, total RAM 32698 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
VAE dtype: torch.float32
Torch version: 2.1.0+cu121
Traceback (most recent call last):
  File "D:\ai3\ComfyUI_9b-re-controlnet\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai3\ComfyUI_9b-re-controlnet\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
  File "D:\ai3\ComfyUI_9b-re-controlnet\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 4, in <module>
    import cv2
  File "D:\ai3\ComfyUI_9b-re-controlnet\python_embeded\Lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "D:\ai3\ComfyUI_9b-re-controlnet\python_embeded\Lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai3\ComfyUI_9b-re-controlnet\python_embeded\Lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "D:\ai3\ComfyUI_9b-re-controlnet\python_embeded\Lib\site-packages\cv2\typing\__init__.py", line 157, in <module>
    Prim = typing.Union[cv2.gapi.wip.draw.Text, cv2.gapi.wip.draw.Circle, cv2.gapi.wip.draw.Image, cv2.gapi.wip.draw.Line, cv2.gapi.wip.draw.Rect, cv2.gapi.wip.draw.Mosaic, cv2.gapi.wip.draw.Poly]
                        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Cannot import D:\ai3\ComfyUI_9b-re-controlnet\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): D:\ai3\ComfyUI_9b-re-controlnet\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.3 seconds: D:\ai3\ComfyUI_9b-re-controlnet\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: D:\ai3\ComfyUI_9b-re-controlnet\ComfyUI\custom_nodes\comfyui-reactor-node

Starting server
```

**Comment by sturentz** [comment]
I can toggle between the two, for example, after Reactor is installed. 
1. Disable in the Manager 
2. Install ControlNetAuxiliary Preprocessors
3. Restart and use
Then when I enable Reactor and restart ControlNetAux is not longer working but Reactor is.

**Comment by Gourieff** [comment]
Try this solution https://github.com/Gourieff/comfyui-reactor-node#iv-controlnet-aux-node-import-failed-error-when-using-with-reactor-node

**Comment by pendave** [comment]
> Try this solution https://github.com/Gourieff/comfyui-reactor-node#iv-controlnet-aux-node-import-failed-error-when-using-with-reactor-node

E:\ComfyUI_Portable\python_embeded>python.exe -m pip install opencv-python==4.7.0.72
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
Collecting opencv-python==4.7.0.72
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/36/98/fab8d982e2e2b57bdebcad64c7e5b5a14ac91c657cac509b9cf3fb
ea49d2/opencv_python-4.7.0.72-cp37-abi3-win_amd64.whl (38.2 MB)
     ---------------------------------------- 38.2/38.2 MB 5.0 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.21.2 in e:\comfyui_portable\python_embeded\lib\site-packages (from opencv-python
==4.7.0.72) (1.25.2)
Installing collected packages: opencv-python
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviou
r is the source of the following dependency conflicts.
inference 0.31.1 requires opencv-python<=4.10.0.84,>=4.8.1.78, but you have opencv-python 4.7.0.72 which is incompatible
.
inference 0.31.1 requires pillow<11.0, but you have pillow 11.0.0 which is incompatible.
inference 0.31.1 requires pillow<11.0,>=9.0.0, but you have pillow 11.0.0 which is incompatible.
inference-cli 0.9.13 requires docker==6.1.3, but you have docker 7.1.0 which is incompatible.
inference-cli 0.9.13 requires requests<=2.31.0, but you have requests 2.32.3 which is incompatible.
inference-gpu 0.9.13 requires pillow<11.0, but you have pillow 11.0.0 which is incompatible.
inference-sdk 0.17.0 requires opencv-python>=4.8.0.0, but you have opencv-python 4.7.0.72 which is incompatible.
simple-lama-inpainting 0.1.2 requires opencv-python<5.0.0.0,>=4.8.0.74, but you have opencv-python 4.7.0.72 which is inc
ompatible.
simple-lama-inpainting 0.1.2 requires pillow<10.0.0,>=9.5.0, but you have pillow 11.0.0 which is incompatible.
Successfully installed opencv-python-4.7.0.72

What's wrong?
