### ISSUE TITLE
install error via node manager

### ISSUE THREAD

**Issue by Atlas3DSS** [Gourieff/comfyui-reactor-node#126]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

had some kind of node conflict so i started a clean install and now for some reason it simply will not actually load - at a complete loss as the first time all i had to do was install via the node manager

it says that the reactor_faceswap.py script isn't in the scripts folder - but it def is i can see it
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/89653506/b03ea0d1-81fc-4f57-851b-5ee25f7991c4)
any help would be appreciated

### Steps to reproduce the problem

literally just trying to basic install it

### Sysinfo

win 11
opera
3090
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/89653506/b6895f35-a312-431c-accf-7ed81755135f)
bare bones on nodes 

### Relevant console log

```Shell
Error log
## ComfyUI-Manager: EXECUTE => ['D:\\dev_genius\\ComfyUI\\comfyui\\Scripts\\python.exe', 'install.py']

## Execute install/(de)activation script for 'D:\dev_genius\ComfyUI\custom_nodes\comfyui-reactor-node'
 Ok

[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
   3.6 seconds: D:\dev_genius\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 130983 MB
xformers version: 0.0.22.post7+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
### Loading: ComfyUI-Manager (V1.6.4)
### ComfyUI Revision: 1779 [9b655d4f] | Released on '2023-12-04'
Traceback (most recent call last):
  File "D:\dev_genius\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\dev_genius\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\dev_genius\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 4, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models, get_current_faces_model, analyze_faces
ModuleNotFoundError: No module named 'scripts.reactor_faceswap'
```

**Comment by Gourieff** [comment]
Hi
What the build of ComfyUI do you use?
Rather unusual folders' structure for Comfy

> D:\dev_genius\ComfyUI\comfyui\Scripts\python.exe

ComfyUI usually goes with "python_embeded" folder in the zero-root ("dev_genius" in your case as I suppose)
Also you have the warning msg about "invalid distribution"
What's you batch file to run?
