### ISSUE TITLE
Getting requirements to build wheel did not run successfully.

### ISSUE THREAD

**Issue by XINXINQIUQIU** [Gourieff/comfyui-reactor-node#128]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

run install.bat error
![QQ截图20231208024445](https://github.com/Gourieff/comfyui-reactor-node/assets/152364881/71551ee9-b665-4452-9a09-68226415cfaf)

### Steps to reproduce the problem

Your workflow
All prerequisite steps have been completed，but run install.bat  error

### Sysinfo

win10    3070

### Relevant console log

```Shell
Installing...
Status: The 'insightface==0.7.3' distribution was not found and is required by the application
Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "O:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "O:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "O:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "O:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "O:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "O:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by Gourieff** [comment]
Insightface lib cannot be built w/o C++ Build Tools
If you don't want to install them - you can try this https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

**Comment by XINXINQIUQIU** [comment]
I have installed Visual Studio 2022 and select "Desktop Development with C++" under "Workloads -> Desktop & Mobile. But it's doesn't work.

**Comment by CRCODE22** [comment]
I have the same problem

**Comment by GamingDaveUk** [comment]
Same issue here (i have visual studios and c++ build tools installed and updated.

I even tried a fresh install

**Comment by EmeranceLN13** [comment]
I solved ! :D 

When running the command https://github.com/Gourieff/comfyui-reactor-node#troubleshooting that is in the trouble shooting section, you actually need to include the whole address of the file.

So the command that worked for me was: D:\ComfyUI\ComfyUI_windows_portable>python.exe -m pip install "D:\ComfyUI\ComfyUI_windows_portable\insightface-0.7.3-cp310-cp310-win_amd64.whl"

Making sure to include the whole path, not just the file's name.
