### ISSUE TITLE
[Feature]: Efficiency Improvement

### ISSUE THREAD

**Issue by hben35096** [Gourieff/comfyui-reactor-node#138]
### Feature description

Hello, I am currently using this plugin for face swapping in videos, and the results are excellent. 
However, I've noticed that the GPU usage during the node processing is almost zero, and the CPU usage is also quite low. It takes around ten minutes to process a few seconds of video. Is it possible to utilize more GPUs or additional CPUs to improve efficiency?
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/139383150/64656207-7ec3-4575-b50a-8c5b57e3acef)
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/139383150/735eca91-5040-4822-aa21-1233fafc0f7a)

Additionally, I have another question regarding some minor visual distortions (screen shaking) around the facial area after face swapping. Could this be due to the facial detection range being too large (I suspect it's because the masking range is rectangular)? If the issue is related to the masking range, would increasing the detection accuracy, for example, using YOLO segmentation, help control the impact within the facial region?

**Comment by Gourieff** [comment]
> Hello, I am currently using this plugin for face swapping in videos, and the results are excellent.
However, I've noticed that the GPU usage during the node processing is almost zero, and the CPU usage is also quite low. It takes around ten minutes to process a few seconds of video. Is it possible to utilize more GPUs or additional CPUs to improve efficiency?

Hi, yes, I have in plans to add threads parameter to increase the processing speed

> Additionally, I have another question regarding some minor visual distortions (screen shaking) around the facial area after face swapping. Could this be due to the facial detection range being too large (I suspect it's because the masking range is rectangular)? If the issue is related to the masking range, would increasing the detection accuracy, for example, using YOLO segmentation, help control the impact within the facial region?

That's right, mask is rectangular (in current version for ComfyUI), it will be resolved soon

**Comment by hben35096** [comment]
> > Hello, I am currently using this plugin for face swapping in videos, and the results are excellent.
> > However, I've noticed that the GPU usage during the node processing is almost zero, and the CPU usage is also quite low. It takes around ten minutes to process a few seconds of video. Is it possible to utilize more GPUs or additional CPUs to improve efficiency?
> 
> Hi, yes, I have in plans to add threads parameter to increase the processing speed
> 
> > Additionally, I have another question regarding some minor visual distortions (screen shaking) around the facial area after face swapping. Could this be due to the facial detection range being too large (I suspect it's because the masking range is rectangular)? If the issue is related to the masking range, would increasing the detection accuracy, for example, using YOLO segmentation, help control the impact within the facial region?
> 
> That's right, mask is rectangular (in current version for ComfyUI), it will be resolved soon

I have two YOLO8 seg models for facial detection here. Please check if they are suitable; you can download them from the ComfyUI manager. If further improvement in detection accuracy is needed, I can attempt to train the next version at some point.
https://github.com/hben35096/assets/releases/tag/yolo8
