### ISSUE TITLE
Won't install after latest update

### ISSUE THREAD

**Issue by IrfanKheiri** [Gourieff/comfyui-reactor-node#142]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Was working fine till last this update.
Now it won't install

### Steps to reproduce the problem

Your workflow
No workflow. The node is not there.
Does not install

### Sysinfo

Windows 11
Latest comfyui version

### Relevant console log

```Shell
Collecting basicsr
  Using cached basicsr-1.4.2.tar.gz (172 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: addict in f:\sd\comfy\python_embeded\lib\site-packages (from basicsr) (2.4.0)
Collecting future (from basicsr)
  Using cached future-0.18.3.tar.gz (840 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Irfan\AppData\Local\Temp\pip-install-mq47vq2q\future_55bb5afbad714e7a83d9aa8c7de76cc5\setup.py", line 86, in <module>
          import src.future
      ModuleNotFoundError: No module named 'src'
      [end of output]
 note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by HWiese1980** [comment]
Confirmed

**Comment by Gourieff** [comment]
https://github.com/Gourieff/comfyui-reactor-node/issues/136#issuecomment-1857890732

**Comment by Gourieff** [comment]
Please update ReActor and run install.bat (inside ReActor's folder)

**Comment by lustfeind** [comment]
How to solve this problem on Mac silicon? I have reinstalled in ComfyUI manager, but still fails to load.

**Comment by IrfanKheiri** [comment]
Cheers. Many thanks. Works now. :)
