### ISSUE TITLE
onnxruntime依赖更新需求

### ISSUE THREAD

**Issue by shenwang2** [Gourieff/comfyui-reactor-node#148]
### Feature description

目前onnxruntime这个python环境只支持cuda11.8，可否更新一下支持更高版本

**Comment by Gourieff** [comment]
This is the official requirements for onnxruntime-gpu https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements

We should wait for the official support of newest CUDA
Or you can try to build ORT by yourself with version of CUDA you need https://github.com/Gourieff/comfyui-reactor-node/issues/119#issuecomment-1841350868

**Comment by motolo** [comment]
I had the same problem and with a pip list I noticed that onnxruntime was at version 0.15, by updating it to version 0.16 I no longer had any problems... I think you need to bring onnx, onnxruntime-gpu and onnxruntime to the latest version and the problems will not they show up...I use cuda at version 121

**Comment by MMoneer** [comment]
Try 
-Uninstall existed  " python_embeded\python.exe -m pip uninstall onnx onnxruntime onnxruntime-gpu"
- Install this version "python_embeded\python.exe -m pip install onnxruntime-gpu==1.14.0 onnxruntime==1.14.0 onnx==1.14.0"

**Comment by murphylanga** [comment]
I found a solution for myself:

1. uninstall everything with the following command in the comfyUI main directory:
python_embeded\python.exe -m pip uninstall onnx onnxruntime onnxruntime-gpu

Then install the following versions:
python_embeded\python.exe -m pip install onnxruntime-gpu==1.16.3 onnxruntime==1.16.3 onnx==1.14.0

I can't guarantee whether this will work for you and I don't know what else it could have an impact on. If you do that, it is your own risk.

Best regards, Murphy
