### ISSUE TITLE
Face index is random

### ISSUE THREAD

**Issue by ckao10301** [Gourieff/comfyui-reactor-node#149]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

1. Need clarification: readme says index goes left to right, then top down. So if there's a face A, face B to the right of A, and face c below face A, what would be the order? A, B, C?
2. From my testing, it's a bit random. See attached photo

### Steps to reproduce the problem

1. Use attached face grid image as input image.
2. change to 0, then 0,1, then 0,1,2, etc. 
3. observe which faces are chosen based on index number.
![Picture1](https://github.com/Gourieff/comfyui-reactor-node/assets/129625358/562c31be-e556-4a57-bad5-19fc15ed389d)
![Picture2](https://github.com/Gourieff/comfyui-reactor-node/assets/129625358/3eae0725-3d2d-480e-9d0d-edb6b4dbfb88)

### Sysinfo

windows

### Relevant console log

```Shell
na
```

**Comment by Gourieff** [comment]
Strange... I will take a look later

**Comment by ckao10301** [comment]
Was this resolved by the new Options node?
