### ISSUE TITLE
After updating comfyui today, an "(IMPORT FAILED)" error occurred.

### ISSUE THREAD

**Issue by merlinmxn** [Gourieff/comfyui-reactor-node#154]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

It has been used normally before. Today, after updating the latest comfyui, the node reports an error.It is normal to use the old version of comfyui.

### Steps to reproduce the problem

An error occurred after updating all from "ComfyUI Manager". I tried reinstalling and only installed the latest ComfyUI and comfyui-reactor-node, but the error still occurred.

### Sysinfo

Win11,Chrome,2080Ti

### Relevant console log

```Shell
** ComfyUI startup time: 2023-12-19 17:58:40.344349
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: E:\SDAI\ComfyUI\cfzy\Scripts\python.exe
** Log path: E:\SDAI\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: E:\SDAI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 22528 MB, total RAM 65438 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
Adding extra search path checkpoints E:\SDAI\sd-webui-aki\models/Stable-diffusion
Adding extra search path configs E:\SDAI\sd-webui-aki\models/Stable-diffusion
Adding extra search path vae E:\SDAI\sd-webui-aki\models/VAE
Adding extra search path loras E:\SDAI\sd-webui-aki\models/Lora
Adding extra search path loras E:\SDAI\sd-webui-aki\models/LyCORIS
Adding extra search path upscale_models E:\SDAI\sd-webui-aki\models/ESRGAN
Adding extra search path upscale_models E:\SDAI\sd-webui-aki\models/RealESRGAN
Adding extra search path upscale_models E:\SDAI\sd-webui-aki\models/SwinIR
Adding extra search path embeddings E:\SDAI\sd-webui-aki\embeddings
Adding extra search path hypernetworks E:\SDAI\sd-webui-aki\models/hypernetworks
Adding extra search path controlnet E:\SDAI\sd-webui-aki\models/ControlNet
### Loading: ComfyUI-Impact-Pack (V4.48.3)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V1.15)
### ComfyUI Revision: 1840 [9a7619b7] | Released on '2023-12-19'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
Total VRAM 22528 MB, total RAM 65438 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
VAE dtype: torch.float32
Torch version: 2.1.2+cu121
Traceback (most recent call last):
  File "E:\SDAI\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\SDAI\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\SDAI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 19, in <module>
    from basicsr.utils.registry import ARCH_REGISTRY
ModuleNotFoundError: No module named 'basicsr'

Cannot import E:\SDAI\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'basicsr'
Comfyroll Custom Nodes: Loaded
[comfyui_controlnet_aux] | INFO -> Using ckpts path: E:\SDAI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\SDAI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 197 nodes successfully.

        "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks." - Mark Zuckerberg


Import times for custom nodes:
   0.0 seconds: E:\SDAI\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: E:\SDAI\ComfyUI\custom_nodes\ComfyUI-seamless-tiling
   0.0 seconds: E:\SDAI\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: E:\SDAI\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
   0.0 seconds: E:\SDAI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: E:\SDAI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds (IMPORT FAILED): E:\SDAI\ComfyUI\custom_nodes\comfyui-reactor-node
   0.4 seconds: E:\SDAI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.5 seconds: E:\SDAI\ComfyUI\custom_nodes\ComfyUI-Manager
   1.0 seconds: E:\SDAI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.3 seconds: E:\SDAI\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\SDAI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
```

**Comment by merlinmxn** [comment]
“pip install basicsr”
The following error occurs, which version should I choose?

> ERROR: Cannot install basicsr==1.3.1, basicsr==1.3.2, basicsr==1.3.3, basicsr==1.3.3.1, basicsr==1.3.3.10, basicsr==1.3.3.11, basicsr==1.3.3.3, basicsr==1.3.3.4, basicsr==1.3.3.5, basicsr==1.3.3.6, basicsr==1.3.3.7, basicsr==1.3.3.8, basicsr==1.3.3.9, basicsr==1.3.4.0, basicsr==1.3.4.1, basicsr==1.3.4.2, basicsr==1.3.4.3, basicsr==1.3.4.4, basicsr==1.3.4.6, basicsr==1.3.4.7, basicsr==1.3.4.8, basicsr==1.3.4.9, basicsr==1.3.5, basicsr==1.4.0, basicsr==1.4.1 and basicsr==1.4.2 because these package versions have conflicting dependencies.

**Comment by Gourieff** [comment]
Try to run install.bat inside the ReActor's folder

**Comment by merlinmxn** [comment]
> Try to run install.bat inside the ReActor's folder

Same error, I didn't use portable,I used the virtual environment git clone to install the entire ComfyUI.In the virtual environment, execute "python install.py",But the error prompt is still the same.

**Comment by RikkB** [comment]
After a fresh install of ComfyUI, and installing comfyui-reactor-node, I ran the install.bat file & got this error 

Installing...
Status: The 'insightface==0.7.3' distribution was not found and is required by the application
Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "C:\Users\rickb\ComfyUI_windows_portable\python_embeded\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\rickb\ComfyUI_windows_portable\python_embeded\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\rickb\ComfyUI_windows_portable\python_embeded\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\rickb\ComfyUI_windows_portable\python_embeded\lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\rickb\ComfyUI_windows_portable\python_embeded\lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\rickb\ComfyUI_windows_portable\python_embeded\lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Any suggestions?

**Comment by Gourieff** [comment]
> Status: The 'insightface==0.7.3' distribution was not found and is required by the application
Collecting insightface==0.7.3
Using cached insightface-0.7.3.tar.gz (439 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... error

https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

**Comment by t0mthab0mb** [comment]
Same thing happened to me today, right after I decided to Update all from comfyui Manager...I was worried, It was difficult for a newbie to python like me to get it going in the first place, a couple months ago. I restarted comfyui and updated all a couple more times and now it works. CMD prompt was pretty busy each time. Perhaps I was behind by a few updates? Well it works now and has a few new bells on it. Thanks for your sharing your work, Gourieff!

**Comment by RikkB** [comment]
> 
> https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

Had something mucked up, but re-re-read this link & followed more closely.  Got it working, thanks for the help Gourieff

**Comment by tetsuoo-online** [comment]
Same here, import failed after updating ComfyUI 2 days ago. I'm looking at this post everyday but It still doesn't work.
I tried to remove all the custom node and it still didn't work so it's really a ComfyUI problem.
When launching ComfyUI I get the error : _ModuleNotFoundError: No module named 'basicsr'_

I think the issue is that when I do :

- python_embeded\python.exe -m pip install future-0.18.3-py3-none-any.whl
- python_embeded\python.exe -m pip install basicsr

...it's trying to put it where Python is installed, and find out it's already there :
_Requirement already satisfied: basicsr in e:\roaming\python\python310\site-packages (1.4.2)_

I can't install it in ComfyUI no matter what. But again, it worked perfectly before the update :/

**Comment by Gourieff** [comment]
> Requirement already satisfied: basicsr in e:\roaming\python\python310\site-packages (1.4.2)

e:\roaming\python\python310 - it's the ComfyUI's "python_embeded" folder - it seems to be your system's python directory

`--force-reinstall` it was a bad idea...
I think, you should better download and install ComfyUI from the scratch

**Comment by tetsuoo-online** [comment]
> > Requirement already satisfied: basicsr in e:\roaming\python\python310\site-packages (1.4.2)
> 
> e:\roaming\python\python310 - it's not the ComfyUI's "python_embeded" folder - it seems to be your system's python directory
> 
> `--force-reinstall` it was a bad idea... I think, you should better download and install ComfyUI from the scratch

So, I reinstalled a new ConfyUI and now everything works BUT Reactor, here we go again xDDD
I won't do force-reinstall this time lol
Maybe having both old Roop and Reactor is bad ? (I wanted to try the old one for science lol)
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/45845308/8bca23b0-1b5b-4f11-a091-54eb1d830015)

In the previous ComfyUI install Reactor/Roop worked fine but not the WAS Node Suite, I wish I could combine the two install xD This is a nightmare hahaha

**Comment by Gourieff** [comment]
The main issue is - that ComfyUI builds don't contain "basicsr" lib (without this lib we cannot adjust Codeformer weight), but "basicsr" cannot be installed without "future" lib which causing errors while trying to be installed in Py311 via simple "pip install"
That's why installation became more complicated

@tetsuoo-online did you run install.bat inside ReActor's folder?

**Comment by tetsuoo-online** [comment]
> > Wait, I'm using Python 3.10.9 is that an issue maybe ?
> 
> You have 3.10.9 in your OS, but ComfyUI's embedded python has 3.11

Dumb question is that okay or... Do I really need to update Python ? This alone might be another headache, at this point who knows what it's going to break xD

I just run install.bat, this is the result...
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/45845308/18af8501-4865-4288-ac07-5b073b97ccda)

**Comment by Gourieff** [comment]
Please update guys
BasicSR is built-in now (inside the ReActor's Node folder)

**Comment by Gourieff** [comment]
> > > Wait, I'm using Python 3.10.9 is that an issue maybe ?
> > 
> > 
> > You have 3.10.9 in your OS, but ComfyUI's embedded python has 3.11
> 
> Dumb question is that okay or... Do I really need to update Python ? This alone might be another headache, at this point who knows what it's going to break xD
> 
> I just run install.bat, this is the result... ![image](https://private-user-images.githubusercontent.com/45845308/292564007-18af8501-4865-4288-ac07-5b073b97ccda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNzEyNzQsIm5iZiI6MTcwMzI3MDk3NCwicGF0aCI6Ii80NTg0NTMwOC8yOTI1NjQwMDctMThhZjg1MDEtNDg2NS00Mjg4LWFjMDctNWIwNzNiOTdjY2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE4NDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOTQ4Y2E1ZWU2ZDVlMWRlMmFkZjJhZTg1MzY3M2VjMTVhMTYzYjEyNTBhZjNlOGRhYzc2NzQ4MjM0ZjIzNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p_YGNAXp0rYAmTNzWei3iJl68fVCbVqubnAdWhyF06c)

No, there's no need to update your system Python, it's ok to have different version for different environments

So, you have an issue with building insightface lib, try to follow these steps: https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild (don't forget to download whl for Py311 - not 310)

**Comment by tetsuoo-online** [comment]
omg everything works now, all fixed. I think I'm gonna cry LOL
2 days struggling xD Thank you

**Comment by tuangd** [comment]
I am still seeing red nodes and "Import Failed" error. 

I ran the "install.bat" inside the folder and this is the error message
```Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.```
---
I think it's the same as @tetsuoo-online
