### ISSUE TITLE
[SOLVED] Embedded python not found. Please install manually. - ERROR: insightface-0.7.3-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by chclkkkk** [Gourieff/comfyui-reactor-node#155]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

When I clicked "install.bat", it said "Embedded python not found. Please install manually". But when I tried to install "insightface-0.7.3-cp310-cp310-win_amd64.whl" into "ComfyUI_windows_portable\python_embeded", it said "ERROR: insightface-0.7.3-cp310-cp310-win_amd64.whl is not a supported wheel on this platform".

### Steps to reproduce the problem

1. Dowload [comfyui-reactor-node](https://github.com/Gourieff/comfyui-reactor-node)
2. Download python 3.10.0
3. Download insightface-0.7.3-cp310-cp310-win_amd64.whl
4. Open cmd in "E:\ComfyUI_windows_portable\python_embeded"
5. Typed "python.exe -m pip install C:\Users\choco\Downloads\insightface-0.7.3-cp310-cp310-win_amd64.whl
6. This note shows up "ERROR: insightface-0.7.3-cp310-cp310-win_amd64.whl is not a supported wheel on this platform."

### Sysinfo

Window 10

### Relevant console log

```Shell
Microsoft Windows [Version 10.0.19045.3803]
(c) Microsoft Corporation. All rights reserved.

E:\ComfyUI_windows_portable\python_embeded>python.exe -m pip install C:\Users\choco\Downloads\insightface-0.7.3-cp310-cp310-win_amd64.whl
ERROR: insightface-0.7.3-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

E:\ComfyUI_windows_portable\python_embeded>
```

### Additional information

When I install "insightface-0.7.3-cp311-cp311-win_amd64.whl" into "E:\ComfyUI_windows_portable\python_embeded" it does install. But when I click on "install.bat" in "E:\comfyui-reactor-node", it says "Embedded python not found. Please install manually.
Press any key to continue . . ."
![image_2023-12-20_125302178](https://github.com/Gourieff/comfyui-reactor-node/assets/154470298/20abe7a4-fd90-4194-b085-3a5f36872612)

**Comment by Gourieff** [comment]
3.10 whl won't be installed on Py3.11

> When I install "insightface-0.7.3-cp311-cp311-win_amd64.whl" into "E:\ComfyUI_windows_portable\python_embeded" it does install. But when I click on "install.bat" in "E:\comfyui-reactor-node", it says "Embedded python not found. Please install manually.
Press any key to continue . . ."

Why do you have ReActor in "E:\comfyui-reactor-node"?
This folder should be inside "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes" - where all ComfyUI custom nodes are stored
That's why ReActor cannot find "Embedded python"

Please follow the installation steps carefully

![изображение](https://github.com/Gourieff/comfyui-reactor-node/assets/85128026/2294caba-914d-4df9-855a-f6d64f8bffa2)

**Comment by chclkkkk** [comment]
Thanks a bunch for fixing that issue. I really appreciate your help!

**Comment by io-tyra** [comment]
grr nothing happens, I'm still stuck, I can't install pulid 

(IMPORT FAILED) [ComfyUI-PuLID-Flux-Enhanced](https://github.com/sipie800/ComfyUI-PuLID-Flux-Enhanced)
Try fix
Uninstall
adapted from https://github.com/balazik/ComfyUI-PuLID-Flux.
common fusion methods for multi-image input, some further experimental fusion methods, switch between using gray image (official) and rgb.,
