### ISSUE TITLE
[SOLVED] Failed to convert an input value to a FLOAT value

### ISSUE THREAD

**Issue by dongyun-kim-arch** [Gourieff/comfyui-reactor-node#159]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Reactor component doesn't work in the certain machine. it's weird that I tried the same workflow in the different machine with the same setting, and it worked.
Couldn't find any issue related to it.

### Steps to reproduce the problem

Your workflow
Just use basic Reactor workflow. Used GFPGAN restoration model and reinaface_resnet50 model.

### Sysinfo

Ubuntu 20.04

### Relevant console log

```Shell
ERROR:root:Failed to validate prompt for output 152:
ERROR:root:* ReActorFaceSwap 149:
ERROR:root:  - Failed to convert an input value to a FLOAT value: face_restore_visibility, no, could not convert string to float: 'no'
ERROR:root:  - Failed to convert an input value to a FLOAT value: codeformer_weight, no, could not convert string to float: 'no'
ERROR:root:  - Value not in list: detect_gender_source: '0' not in ['no', 'female', 'male']
ERROR:root:  - Value not in list: detect_gender_input: '0' not in ['no', 'female', 'male']
ERROR:root:Output will be ignored
```

**Comment by Gourieff** [comment]
Delete an existing ReActor's Node from your workflow and add it again

**Comment by 2PeteShakur** [comment]
thanks, working fine now! ;)
