### ISSUE TITLE
[SOLVED] ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

### ISSUE THREAD

**Issue by alessandroperilli** [Gourieff/comfyui-reactor-node#161]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

The last couple of updates to this custom node suite have caused the following error:

>   File "xyz/ComfyUI/nodes.py", line 1813, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "xyz/ComfyUI/custom_nodes/comfyui-reactor-node/__init__.py", line 25, in <module>
>     from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
>   File "xyz/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 19, in <module>
>     from basicsr.utils.registry import ARCH_REGISTRY
>   File "xyz/ComfyUI/custom_nodes/comfyui-reactor-node/basicsr/__init__.py", line 4, in <module>
>     from .data import *
>   File "xyz/ComfyUI/custom_nodes/comfyui-reactor-node/basicsr/data/__init__.py", line 22, in <module>
>     _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/ComfyUI/custom_nodes/comfyui-reactor-node/basicsr/data/__init__.py", line 22, in <listcomp>
>     _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/ComfyUI/custom_nodes/comfyui-reactor-node/basicsr/data/realesrgan_dataset.py", line 11, in <module>
>     from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
>   File "xyz/ComfyUI/custom_nodes/comfyui-reactor-node/basicsr/data/degradations.py", line 8, in <module>
>     from torchvision.transforms.functional_tensor import rgb_to_grayscale
> ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'
> 
> Cannot import xyz/ComfyUI/custom_nodes/comfyui-reactor-node module for custom nodes: No module named 'torchvision.transforms.functional_tensor'

### Steps to reproduce the problem

Just update the node suite to the latest version via ComfyUI Manager.

### Sysinfo

Apple M2

### Relevant console log

```Shell
>   File "xyz/ComfyUI/nodes.py", line 1813, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "xyz/ComfyUI/custom_nodes/comfyui-reactor-node/__init__.py", line 25, in <module>
>     from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
>   File "xyz/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 19, in <module>
>     from basicsr.utils.registry import ARCH_REGISTRY
>   File "xyz/ComfyUI/custom_nodes/comfyui-reactor-node/basicsr/__init__.py", line 4, in <module>
>     from .data import *
>   File "xyz/ComfyUI/custom_nodes/comfyui-reactor-node/basicsr/data/__init__.py", line 22, in <module>
>     _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/ComfyUI/custom_nodes/comfyui-reactor-node/basicsr/data/__init__.py", line 22, in <listcomp>
>     _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/ComfyUI/custom_nodes/comfyui-reactor-node/basicsr/data/realesrgan_dataset.py", line 11, in <module>
>     from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
>   File "xyz/ComfyUI/custom_nodes/comfyui-reactor-node/basicsr/data/degradations.py", line 8, in <module>
>     from torchvision.transforms.functional_tensor import rgb_to_grayscale
> ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'
> 
> Cannot import xyz/ComfyUI/custom_nodes/comfyui-reactor-node module for custom nodes: No module named 'torchvision.transforms.functional_tensor'
```

### Additional information

The solution to this problem is described here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13985#issuecomment-1814870368

**Comment by Th3Rom3** [comment]
The solution in https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13985#issuecomment-1814870368 worked well for me. Change line 8 in
`/ComfyUI/custom_nodes/comfyui-reactor-node/basicsr/data/`
from
`from torchvision.transforms.functional_tensor import rgb_to_grayscale`
to
`from torchvision.transforms.functional import rgb_to_grayscale`

**Comment by alessandroperilli** [comment]
Thanks!
