### ISSUE TITLE
from insightface.app.common import Face /// ModuleNotFoundError: No module named 'insightface'

### ISSUE THREAD

**Issue by Nomikibasu** [Gourieff/comfyui-reactor-node#164]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Trying to run run_nvidia_gpu.bat the custom node import failed

### Steps to reproduce the problem

Your workflow
1. typed python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl in the cmd after placing the file in the root folder
2. ran  run_nvidia_gpu.bat

### Sysinfo

Windows 11

### Relevant console log

```Shell
Traceback (most recent call last):
  File "C:\Users\ginot\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ginot\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\ginot\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 14, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models, get_current_faces_model, analyze_faces
  File "C:\Users\ginot\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 12, in <module>
    from scripts.reactor_logger import logger
  File "C:\Users\ginot\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_logger.py", line 6, in <module>
    from reactor_utils import addLoggingLevel
  File "C:\Users\ginot\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_utils.py", line 8, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

Cannot import C:\Users\ginot\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
```

### Additional information

Code when trying to install insightface again:
PS C:\Users\ginot\ComfyUI_windows_portable> python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl
Processing c:\users\ginot\comfyui_windows_portable\insightface-0.7.3-cp311-cp311-win_amd64.whl
Requirement already satisfied: numpy in c:\users\ginot\appdata\roaming\python\python311\site-packages (from insightface==0.7.3) (1.26.2)
Requirement already satisfied: onnx in c:\users\ginot\appdata\roaming\python\python311\site-packages (from insightface==0.7.3) (1.15.0)
Requirement already satisfied: tqdm in c:\users\ginot\appdata\roaming\python\python311\site-packages (from insightface==0.7.3) (4.66.1)
Requirement already satisfied: requests in c:\users\ginot\appdata\roaming\python\python311\site-packages (from insightface==0.7.3) (2.31.0)
Requirement already satisfied: matplotlib in c:\users\ginot\appdata\roaming\python\python311\site-packages (from insightface==0.7.3) (3.8.2)
Requirement already satisfied: Pillow in c:\users\ginot\appdata\roaming\python\python311\site-packages (from insightface==0.7.3) (9.5.0)
Requirement already satisfied: scipy in c:\users\ginot\appdata\roaming\python\python311\site-packages (from insightface==0.7.3) (1.11.4)
Requirement already satisfied: scikit-learn in c:\users\ginot\appdata\roaming\python\python311\site-packages (from insightface==0.7.3) (1.3.2)
Requirement already satisfied: scikit-image in c:\users\ginot\appdata\roaming\python\python311\site-packages (from insightface==0.7.3) (0.22.0)
Requirement already satisfied: easydict in c:\users\ginot\appdata\roaming\python\python311\site-packages (from insightface==0.7.3) (1.11)
Requirement already satisfied: cython in c:\users\ginot\appdata\roaming\python\python311\site-packages (from insightface==0.7.3) (3.0.7)
Requirement already satisfied: albumentations in c:\users\ginot\appdata\roaming\python\python311\site-packages (from insightface==0.7.3) (1.3.1)
Requirement already satisfied: prettytable in c:\users\ginot\appdata\roaming\python\python311\site-packages (from insightface==0.7.3) (3.9.0)
Requirement already satisfied: PyYAML in c:\users\ginot\appdata\roaming\python\python311\site-packages (from albumentations->insightface==0.7.3) (6.0.1)
Requirement already satisfied: qudida>=0.0.4 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from albumentations->insightface==0.7.3) (0.0.4)
Requirement already satisfied: opencv-python-headless>=4.1.1 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from albumentations->insightface==0.7.3) (4.8.1.78)
Requirement already satisfied: networkx>=2.8 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from scikit-image->insightface==0.7.3) (3.2.1)
Requirement already satisfied: imageio>=2.27 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from scikit-image->insightface==0.7.3) (2.33.1)
Requirement already satisfied: tifffile>=2022.8.12 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from scikit-image->insightface==0.7.3) (2023.12.9)
Requirement already satisfied: packaging>=21 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from scikit-image->insightface==0.7.3) (23.2)
Requirement already satisfied: lazy_loader>=0.3 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from scikit-image->insightface==0.7.3) (0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from matplotlib->insightface==0.7.3) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from matplotlib->insightface==0.7.3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from matplotlib->insightface==0.7.3) (4.47.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from matplotlib->insightface==0.7.3) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from matplotlib->insightface==0.7.3) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from matplotlib->insightface==0.7.3) (2.8.2)
Requirement already satisfied: protobuf>=3.20.2 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from onnx->insightface==0.7.3) (4.25.1)
Requirement already satisfied: wcwidth in c:\users\ginot\appdata\roaming\python\python311\site-packages (from prettytable->insightface==0.7.3) (0.2.12)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from requests->insightface==0.7.3) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from requests->insightface==0.7.3) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from requests->insightface==0.7.3) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from requests->insightface==0.7.3) (2023.11.17)
Requirement already satisfied: joblib>=1.1.1 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from scikit-learn->insightface==0.7.3) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from scikit-learn->insightface==0.7.3) (3.2.0)
Requirement already satisfied: colorama in c:\users\ginot\appdata\roaming\python\python311\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\ginot\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3) (1.16.0)
Requirement already satisfied: typing-extensions in c:\users\ginot\appdata\roaming\python\python311\site-packages (from qudida>=0.0.4->albumentations->insightface==0.7.3) (4.9.0)
insightface is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.

**Comment by MMoneer** [comment]
Try to install with force-reinstall :
python_embeded\python.exe -m pip install --upgrade --force-reinstall insightface-0.7.3-cp311-cp311-win_amd64.whl

**Comment by Nomikibasu** [comment]
> Try to install with force-reinstall : python_embeded\python.exe -m pip install --upgrade --force-reinstall insightface-0.7.3-cp311-cp311-win_amd64.whl

Thank you alot, that worked.

**Comment by rendomnet** [comment]
WARNING: Requirement 'insightface-0.7.3-cp311-cp311-win_amd64.whl' looks like a filename, but the file does not exist

**Comment by MMoneer** [comment]
> WARNING: Requirement 'insightface-0.7.3-cp311-cp311-win_amd64.whl' looks like a filename, but the file does not exist

you have to download it (as comfyui-reactor-node troubleshoot instruction) and put it in the ComfyUI_windows_portable root folder beside run_nvidia_gpu.bat
