### ISSUE TITLE
Save Face Model Error - List Index Out of Range

### ISSUE THREAD

**Issue by NolenBrolen** [Gourieff/comfyui-reactor-node#166]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

When I try to follow the example on the page to connect the LoadImage node to the SaveFaceModel node, and run the pipeline, I get the error stacktrace below. I checked other issues, and saw there was someone else experiencing this same error, and there was a fix deployed for that issue on 3a63046. I made sure to git fetch and git pull to be on latest branch but the error persists.

### Steps to reproduce the problem

[workflow_example.json](https://github.com/Gourieff/comfyui-reactor-node/files/13788767/workflow_example.json)
- Load Image Node
- Connect to SaveFaceModel Node
- Queue prompt

### Sysinfo

Windows 10
NVIDIA GeForce RTX 3060
Google Chrome

### Relevant console log

```Shell
`got prompt
[ReActor] 19:51:29 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 19:51:29 - STATUS - Analyzing Source Image...
[ReActor] 19:51:30 - STATUS - Using Hashed Target Face(s) Model...
[ReActor] 19:51:30 - STATUS - Trying to halve 'det_size' parameter
[ReActor] 19:51:31 - STATUS - Swapping...
[ReActor] 19:51:31 - STATUS - --Done!--
[ReActor] 19:51:31 - STATUS - Restoring with codeformer.pth
[ReActor] 19:51:33 - ERROR - Please provide 'source_image' or `face_model`
[ReActor] 19:51:33 - STATUS - Building Face Model...
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Users\G4G\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G4G\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G4G\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\G4G\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 278, in save_model
    face_model = analyze_faces(source)[0]
                 ~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

Prompt executed in 4.79 seconds`
```

**Comment by Ehesh** [comment]
Same error here, same steps

Sysinfo
Windows 11
CPU
Edge

**Comment by Gourieff** [comment]
This error can appear only if you have no face in the analysing image
I've just test it and it works great if there's at least one human face on a photo

**Comment by NolenBrolen** [comment]
> This error can appear only if you have no face in the analysing image I've just test it and it works great if there's at least one human face on a photo

Thanks for this tip, I used the PrepImageForInsighFace from the IP-adapter Plus Node, and that fixed it. So it seems I was uploading images with too little information around them. 

Here in this video the Owner of the IP-Adapter Plus Node showcases the use case for IP-adapter, but this can also be applied to creating an Embedding of a Face, and fixes this error: https://youtu.be/jSu_tKfg5rI?si=yAGxr2FDKqkrXMIk&t=222
