### ISSUE TITLE
[Feature]: GPEN-BFR-512 support

### ISSUE THREAD

**Issue by rugabunda** [Gourieff/comfyui-reactor-node#175]
### Feature description

Its available within [facefusion](https://github.com/facefusion/facefusion) as a face enhancer, in onnx format, and in facefusion I found it to be superior to gfpgan 1.4, making for more realistic and sharper faces.

It can be downloaded here, https://public-vigen-video.oss-cn-shanghai.aliyuncs.com/robin/models/GPEN-BFR-512.pth
Apparently they also have 1024 & 2048 versions as well.

I attempted to use the .pth version in reactor it but it pushed an error that it was an incompatible model.

**Comment by Gourieff** [comment]
Yes, I have in plans to add its support in future updates

**Comment by rugabunda** [comment]
> Yes, I have in plans to add its support in future updates

Wonderful! Thank you!

**Comment by camoody1** [comment]
Following!

**Comment by Mozoloa** [comment]
> Yes, I have in plans to add its support in future updates

Oh nice, just discovered this in facefusion and it's pretty impressive, eager to see it in reactor

**Comment by Gourieff** [comment]
Done! https://github.com/Gourieff/comfyui-reactor-node#042-beta2

**Comment by camoody1** [comment]
Thank you!

**Comment by TheBlackHacker** [comment]
I'm facing this issue when using the onnx model, do onnx model work in this patch?
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/8444126/fbad7beb-d2eb-40f0-ad8b-db1d117e584b)

**Comment by Mozoloa** [comment]
I've tried adding the 1024 and 2048 GPEN models in the folder, but they don't seem to work out of the box

Error occurred when executing ReActorFaceSwap:

local variable 'cropped_face_t' referenced before assignment

```
File "G:\AI\Image\Stable Diffusion\Data\Packages\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "G:\AI\Image\Stable Diffusion\Data\Packages\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "G:\AI\Image\Stable Diffusion\Data\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "G:\AI\Image\Stable Diffusion\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 301, in execute
result = reactor.restore_face(self,result,face_restore_model,face_restore_visibility,codeformer_weight,facedetection)
File "G:\AI\Image\Stable Diffusion\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 234, in restore_face
restored_face = tensor2img(cropped_face_t, rgb2bgr=True, min_max=(-1, 1))
```
