### ISSUE TITLE
Trouble Installing on Linux-What are the instructions?

### ISSUE THREAD

**Issue by ckao10301** [Gourieff/comfyui-reactor-node#177]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I'm trying to install on comfyui for ubuntu-what do I need to do aside from cloning the node repo?. The installation instructions are for windows and webui

SD WebUI: [AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui/) or [SD.Next](https://github.com/vladmandic/automatic)
Close (stop) your SD-WebUI/Comfy Server if it's running
(For Windows Users):
Install [Visual Studio 2022](https://visualstudio.microsoft.com/downloads/) (Community version - you need this step to build Insightface)
OR only [VS C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/) and select "Desktop Development with C++" under "Workloads -> Desktop & Mobile"
OR if you don't want to install VS or VS C++ BT - follow [this steps (sec. I)](https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#insightfacebuild)
Go to the extensions\sd-webui-comfyui\ComfyUI\custom_nodes
Open Console or Terminal and run git clone https://github.com/Gourieff/comfyui-reactor-node
Go to the SD WebUI root folder, open Console or Terminal and run (Windows users).\venv\Scripts\activate or (Linux/MacOS)venv/bin/activate
python -m pip install -U pip
cd extensions\sd-webui-comfyui\ComfyUI\custom_nodes\comfyui-reactor-node
python install.py
Please, wait until the installation process will be finished
(From the version 0.3.0) Download facerestorers models from the links below and put them into the extensions\sd-webui-comfyui\ComfyUI\custom_nodes\comfyui-reactor-node\models\facerestore_models directory:
CodeFormer: https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth
GFPGAN: https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth
Run SD WebUI and check console for the message that ReActor Node is running:

### Steps to reproduce the problem

Your workflow

### Sysinfo

mint linux (ubuntu)

### Relevant console log

```Shell
na
```

**Comment by M1chol** [comment]
Hi, I just looked at install.bat and all it does is:
1. checks if python is installed
2. runs install.py

so all you need to do after cloning is to run install.py in your venv/system.
Worked for me

**Comment by ckao10301** [comment]
@M1chol thanks that did work!
