### ISSUE TITLE
[Feature]: Combine multiple source face images for single face swap and face model creation.

### ISSUE THREAD

**Issue by StellarBeing25** [Gourieff/comfyui-reactor-node#184]
### Feature description

Please give the option to combine multiple source face images using batch image nodes for a single face swap and face model creation to get better face likeness.

**Comment by StellarBeing25** [comment]
Just wanted to add that this feature is already present in Rope face swapper app. Here is the demo video showing combine source faces feature - https://www.youtube.com/watch?v=zsgRc3opT68

**Comment by Gourieff** [comment]
Yes, this is in the list

**Comment by recycleaway7** [comment]
I just figured out a workaround for this for anyone interested. I've only tested it twice but it worked both times. Let's say you want to use 4 face images as inputs for the reactor face model. Start by training 4 separate face models, 1 from each face image. Then merge all 4 face models together into one. I'm not sure how to do this in ComfyUI so I did it in the Checkpoint Merger tab in A1111.

ModelA=face1, ModelB=face 2, multiplier=0.5, weighted sum, merge to create merge1
ModelA=face3, ModelB=face4, multiplier=0.5, weighted sum, merge to create merge2

ModelA=merge1, ModelB=merge 2, multiplier=0.5, weighted sum, merge to create final face model

Curious if anyone else has success with this approach or if they can whip up a workflow to automate.

**Comment by recycleaway7** [comment]
> > I just figured out a workaround for this for anyone interested. I've only tested it twice but it worked both times. Let's say you want to use 4 face images as inputs for the reactor face model. Start by creating 4 separate reactor face models using the comfyui node, 1 from each face image. Then merge all 4 face models together into one. I'm not sure how to do this in ComfyUI so I did it in the Checkpoint Merger tab in A1111.
> > ModelA=face1, ModelB=face2, multiplier=0.5, weighted sum, merge to create merge1 ModelA=face3, ModelB=face4, multiplier=0.5, weighted sum, merge to create merge2
> > ModelA=merge1, ModelB=merge2, multiplier=0.5, weighted sum, merge to create final face model
> > Curious if anyone else has success with this approach or if they can whip up a workflow to automate.
> 
> tried it, but the ModelA always wins, there's no different between mixed models and ModelA when compared.

Have you tried with 2 completely different faces yet? The first thing I tried was mixing 2 different people and from what I remember I ended up with a blend of the 2. If you leave multiplier at 0.3 and forget to change to 0.5 then model A will dominate a lot. I'll have to test a bit more.

**Comment by b8kings0ga** [comment]
yes, that would be helpfull

**Comment by Musigreg** [comment]
> Yes, this is in the list

Do we have any idea when this would be implemented ?

**Comment by WesleyKapow** [comment]
Would love to be able to create a face model easily from many photos and then feed that into reactor!

**Comment by andreclaudino** [comment]
+1 for this

**Comment by Gourieff** [comment]
Done! https://github.com/Gourieff/comfyui-reactor-node#042-beta1

**Comment by StellarBeing25** [comment]
Nice, but is it possible to faceswap directly with multiple source faces without creating a model first so that reactor can be directly used in the workflows with multiple face images like FaceID portrait?
