### ISSUE TITLE
inswapper_128.onnx is only swap_model which works

### ISSUE THREAD

**Issue by tobiaswuerth** [Gourieff/comfyui-reactor-node#187]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

as indicated by the instructions, [the following models are supported](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md#safe-to-use-models-have-the-folowing-hash). I downloaded them and put them into the `\ComfyUI\models\insightface` folder. When executing the main node like this
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/21124705/d598be69-a827-47cc-8c54-245ce4c439e4)
I get the following exception:
```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\_projects\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_projects\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_projects\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 112, in execute
    script.process(
  File "D:\_projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 96, in process
    result = swap_face(
             ^^^^^^^^^^
  File "D:\_projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 258, in swap_face
    result = face_swapper.get(result, target_face, source_face)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ArcFaceONNX.get() takes 3 positional arguments but 4 were given
```

### Steps to reproduce the problem

amo

### Sysinfo

win 11, edge, RTX 2080TI

### Relevant console log

```Shell
amo
```

**Comment by Gourieff** [comment]
> as indicated by the instructions, [the following models are supported](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md#safe-to-use-models-have-the-folowing-hash). I downloaded them and put them into the \ComfyUI\models\insightface folder. When executing the main node like this

These models (1k3d68.onnx, 2d106det.onnx, det_10g.onnx, genderage.onnx, w600k_r50.onnx) are analyzing models, not swap_models
The only one swap model here is the inswapper model (inswapper_128.onnx)
Scripts downloads analyzing models automatically into "ComfyUI\models\insightface\models\buffalo_l"
No word in the instruction says that you need to download these models and use them as swapper models
Current version of ReActor Node (0.4.1 beta4) downloads automatically all the models you need - except the face restoration models (which you should download manually)

**Comment by tobiaswuerth** [comment]
ah I see, I completly misunderstood then.
What other models besides inswapper_128 are supported then?

**Comment by tobiaswuerth** [comment]
okay, thanks for the information :)
