### ISSUE TITLE
ReActor does not respond to "cancel" signal from ComfyUI

### ISSUE THREAD

**Issue by darkpixel** [Gourieff/comfyui-reactor-node#188]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

When you click the "cancel" button in the queue next to a job, most processes in ComfyUI stop within a few seconds and the job is abandoned.  If you click "cancel" while ReActor is running, it will wait to finish swapping faces for all the images before discarding the output.  If it has an image batch of...say...50 images, it may swap faces for several minutes before finishing and then doing nothing with the output.

**Comment by Gourieff** [comment]
Yes, this will be fixed soon

**Comment by Gourieff** [comment]
Fixed!
