### ISSUE TITLE
Error not installing

### ISSUE THREAD

**Issue by eimonpakzad** [Gourieff/comfyui-reactor-node#192]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

 this error is showing after installing install.bat "mesh_core_cython.cpp
      insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpp(36): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects" please help me

### Steps to reproduce the problem

Your workflow
n/a

### Sysinfo

Windows 11 and python 11.6

### Relevant console log

```Shell
n/a
```

**Comment by evanerichards** [comment]
I have this same issue. Except I'm on Windows 10

**Comment by jleaders** [comment]
Same on Windows 11

**Comment by cuncinc** [comment]
This worked for me: 
1. go to [here](https://huggingface.co/hanamizuki-ai/insightface-releases/blob/main/insightface-0.7.3-cp311-cp311-win_amd64.whl) download the whl file and move it into project folder.
2. open a terminal an cd to path, and type `.\python_embeded\python.exe -m pip install .\insightface-0.7.3-cp311-cp311-win_amd64.whl`
