### ISSUE TITLE
[Feature]: Alternative for innswapper

### ISSUE THREAD

**Issue by chaincrafter** [Gourieff/comfyui-reactor-node#196]
### Feature description

Can you point us in a direction on how we can change the innswapper_128 model? Like train another or something.
As the innswapper128 is really bad for images larger than 512x512...

**Comment by Gourieff** [comment]
The main issue is that the Insightface team rejected to provide for the Community any specifications about how to train such models as inswapper... 
There are some other models as SimSwap, Blendface - but they have less accuracy then Inswapper has even with 128x128 resolution
https://github.com/Gourieff/sd-webui-reactor/issues/261

So... The best model at the moment that the Community has for free - is inswapper_128
But it's just a matter of time when we will get a new model with better quality
