### ISSUE TITLE
Large amount of VRAM remain filled after face swap is completed.

### ISSUE THREAD

**Issue by StellarBeing25** [Gourieff/comfyui-reactor-node#202]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Whenever reactor face swap node is used in the workflow, it does not get unloaded from the VRAM after completing the swap process leading to out of memory error  when the workflow is executed for the second time. VRAM usage before & after swap is shown in the screenshot below.
![B](https://github.com/Gourieff/comfyui-reactor-node/assets/152368658/82d7ca9a-10ee-47f1-9b15-0280ce72da71)
![A](https://github.com/Gourieff/comfyui-reactor-node/assets/152368658/57079050-e036-4c12-aa41-575f958f8a1d)

### Steps to reproduce the problem

Your workflow
Use reactor node anywhere in the workflow.

### Sysinfo

OS - Windows 11
GPU - Nvidia GTX 1660 6GB

### Relevant console log

```Shell
No Log available for the issue.
```

**Comment by Gourieff** [comment]
Yes, know Issue https://github.com/Gourieff/sd-webui-reactor/issues/307#issuecomment-1876994178

**Comment by Gourieff** [comment]
You can uninstall ORT-GPU an install ORT, the swapping process will be a bit slower but no VRAM will be utilized by ReActor
