### ISSUE TITLE
The remote edge becomes blurry when changing a large face.

### ISSUE THREAD

**Issue by zhangp365** [Gourieff/comfyui-reactor-node#207]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

The title suggests that when changing the large face in the picture, such as the one below:
![2](https://github.com/Gourieff/comfyui-reactor-node/assets/144313702/1e333f3f-3886-4783-93f9-ba411c8ed2f0)
I consistently achieve a perfect face but with a blurry edge, as shown here:
![2out](https://github.com/Gourieff/comfyui-reactor-node/assets/144313702/80f3889b-75a4-4e3c-82fa-dfbb0caec43d)
Is there a way to adjust some swap face parameters to alleviate this issue? Thank you."

### Steps to reproduce the problem

My workflow is the default one. 
![workflow](https://github.com/Gourieff/comfyui-reactor-node/assets/144313702/3edb6f78-277d-46db-af59-dcdce9e1bd6d)

### Sysinfo

win11, chrome, 3070ti, 8g

### Relevant console log

```Shell
no exception.
```

**Comment by Gourieff** [comment]
Hi, you can try my workflow with mask correction https://boosty.to/artgourieff/posts/e3e5be09-69f4-4c4f-acf8-1fab18929d76
Or you can swap via A1111 (sd-webui-reactor already has this option)

**Comment by Develeste** [comment]
I also have the same trouble.

![image](https://github.com/Gourieff/comfyui-reactor-node/assets/93141030/302dff11-a122-4737-bdbc-5a58c289f486)

**Comment by Gourieff** [comment]
Just add the face masking nodes after ReActor (detection, cut by mask from the swapped one, past by mask to the ref or generated) and you will get a perfect result with no pixelization

**Comment by Gourieff** [comment]
Solved in 0.5.0-a1 https://github.com/Gourieff/comfyui-reactor-node#050-alpha1
