### ISSUE TITLE
[Feature]: insightface for python 12. 

### ISSUE THREAD

**Issue by ShalolaAuthor** [Gourieff/comfyui-reactor-node#219]
### Feature description

comfyui just updated a nightly build using python 12. i tried renaming the install file to cp312 manually. but built has failed.

**Comment by Gourieff** [comment]
It won't work like that
And a lot of dependencies as e.g. onnx and onnxruntime also cannot work with Py3.12 yet, it's too early to update to 3.12

**Comment by ShalolaAuthor** [comment]
> @ShalolaAuthor Hi Py3.12 Insightface package is ready https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp312-cp312-win_amd64.whl Feel free to test There can be the error during installation about ONNX lib - you should manually git clone latest https://github.com/onnx/onnx and install requirements and then try again

cheers, thanks a lot, i see that onnxruntime is also updated to 1.17 for cp312.
