### ISSUE TITLE
Lots of connection errors in the console after the face restore models gets downloaded.

### ISSUE THREAD

**Issue by StellarBeing25** [Gourieff/comfyui-reactor-node#221]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?
Getting connection errors after the models get downloaded successfully even on different Internet connections and VPN servers. 

![Issue Screenshot-Reactor Node](https://github.com/Gourieff/comfyui-reactor-node/assets/152368658/fc2f5e55-402b-4636-b2cd-3daa79c433ee)

### Steps to reproduce the problem

Fresh install ComfyUI and Reactor node.

### Sysinfo

Windows 11
Anaconda venv (Python 3.11)
GPU- Nvidia GTX 1660 6GB

### Relevant console log

```Shell
Log not available.
```

**Comment by Gourieff** [comment]
You had networks errors
ReActor has nothing to do with this
