### ISSUE TITLE
Lacking main model of comfyui-reactor-node, no any file in insightface folder as well, how can it be solved?

### ISSUE THREAD

**Issue by Jerrrrrrrrrrrrrrrrrry** [Gourieff/comfyui-reactor-node#232]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

![微信截图_20240223145812](https://github.com/Gourieff/comfyui-reactor-node/assets/161010033/2835a442-0467-4f0a-9071-da3ed3382cc4)
![微信截图_20240223145753](https://github.com/Gourieff/comfyui-reactor-node/assets/161010033/554dfc75-f192-4992-9910-bc68454cd0d4)

### Steps to reproduce the problem

After the installation, the main model choice in "Reactor" is missing as can be seen in the pic.

### Sysinfo

Window 10, Edge & Chrome, RTX2060.

### Relevant console log

```Shell
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
```

### Additional information

the insightface folder is empty as well

**Comment by mashiye** [comment]
the  same problem

**Comment by Gourieff** [comment]
Related https://github.com/Gourieff/comfyui-reactor-node/issues/244

**Comment by Gourieff** [comment]
@Jerrrrrrrrrrrrrrrrrry please provide your log

**Comment by amazingbiubiu** [comment]
the same problem

**Comment by Gourieff** [comment]
Provide your logs guys
There should be any errors in the Console

**Comment by jiangzw2013** [comment]
同样的问题 请问有解决吗？
