### ISSUE TITLE
[Feature]: Many photos to create face model

### ISSUE THREAD

**Issue by seghier** [Gourieff/comfyui-reactor-node#241]
### Feature description

Very useful and easy
Can you add a feature to use different photos to create a face model?
One photo is good but i think more photos will make the result better

**Comment by Gourieff** [comment]
Yes, this is in the road map
But already now you can create blended face models in SD WebUI (A1111/SD.Next/Forge) via sd-webui-reactor and then use them in ComfyUI
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/85128026/206a3fa6-1ed8-46ca-8aed-b388effc61d3)

**Comment by Gourieff** [comment]
Done! https://github.com/Gourieff/comfyui-reactor-node#042-beta1

**Comment by seghier** [comment]
Very nice, thank you

**Comment by Mozoloa** [comment]
I'm trying to use the new build blended face model, but there's no indication as to where it's saved, any idea ?
