### ISSUE TITLE
[SOLVED] IMPORT FAILED

### ISSUE THREAD

**Issue by Trobinou** [Gourieff/comfyui-reactor-node#25]
The installation is trouble-free from the Manager, and the model inswapper_128.onnx is downloaded correctly.
When launching ComfyUI, I get the following error message in the console: 'Import Failed'.
I have no other error messages, and, of course, the Reactor node is not available. I've had this problem since I first tried to install it over a week ago. I waited for yesterday's update before uninstalling and reinstalling it, but the result is the same.
What information would you need to find a solution?

**Comment by Gourieff** [comment]
Show please your Console log
What other nodes do you have enabled?

**Comment by Trobinou** [comment]
Here are the other nodes: 
0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\recommended_res_calc.py
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Camera_Styler
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\theme_Styler
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\subject_Styler
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\depth_Styler
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Composition_Styler
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lighting_Styler
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Mood_Styler
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Filter_Styler
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Focus_Styler
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui-main
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes-master
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Environment_Styler
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyI2I
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Time_of_Day_Styler
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Bmad-DirtyUndoRedo
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\wlsh_nodes-main
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_model_merging.py
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\images-grid-comfy-plugin-main
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\OneButtonPrompt
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\failfast-comfyui-extensions
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
   0.2 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\clipseg.py
   0.3 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.3 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.4 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors
   0.7 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   0.8 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

**Comment by Gourieff** [comment]
According to this Issue https://github.com/Gourieff/comfyui-reactor-node/issues/24 "was-node-suite-comfyui" can cause the dependencies conflict
You can try this solution:
https://github.com/Gourieff/comfyui-reactor-node/issues/24#issuecomment-1715007582

**Comment by Trobinou** [comment]
Thank you very much, I'll look into it.

**Comment by Gourieff** [comment]
> ModuleNotFoundError: No module named 'insightface'

This is the reason
Probably you have no VS 2022 or VS C++ Build Tools in your OS
Insightface cannot be built without C++ Build Tools

But you can install pre-built package by following these steps:
https://github.com/Gourieff/comfyui-reactor-node#i-for-windows-users-if-you-still-cannot-build-insightface-for-some-reasons-or-just-dont-want-to-install-visual-studio-or-vs-c-build-tools---do-the-following

**Comment by Trobinou** [comment]
Fantastic, everything works! Thank you so much for your help and patience :)

**Comment by Gourieff** [comment]
You're welcome! Glad to help

**Comment by chieeo** [comment]
0.0 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\PowerNoiseSuite
   0.0 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\images-grid-comfy-plugin
   0.0 seconds (IMPORT FAILED): C:\ComfyUI-aki-v1.3\custom_nodes\rgthree-comfy
   0.0 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_experiments
   0.0 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-layerdiffuse
   0.0 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds (IMPORT FAILED): C:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Marigold
   0.0 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\comfyui-workspace-manager
   0.0 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Inspire-Pack
   0.2 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-KJNodes
   0.2 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\facerestore_cf
   0.4 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_FizzNodes
   0.5 seconds (IMPORT FAILED): C:\ComfyUI-aki-v1.3\custom_nodes\comfyui-reactor-node
   0.6 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-InstantID
   0.6 seconds: C:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager
