### ISSUE TITLE
[Feature]: Ability to face swap directly using multiple source faces.  

### ISSUE THREAD

**Issue by StellarBeing25** [Gourieff/comfyui-reactor-node#253]
### Feature description

The current implementation for using multiple source faces requires face model creation, which requires running two different workflows when combining reactor with IP adapters face nodes for blending multiple faces together. Please add the option for direct face swap using multiple source faces. Below is the workflow screenshot for the FaceID Portrait IP Adapter. It would be nice to use reactor node directly in such workflows to achieve perfect face swap.
![FaceID Portrait Workflow](https://github.com/Gourieff/comfyui-reactor-node/assets/152368658/16cea498-7c82-436b-97a1-b286c71ae30f)

**Comment by Gourieff** [comment]
Good idea 👍 Thanks

**Comment by KINGLIFER** [comment]
If this has been added may I ask how to implement? I did a request here and not sure if this is the same.
