### ISSUE TITLE
macOS Big Sur 11.7.10 (intel) installation error / No module named 'folder_paths'

### ISSUE THREAD

**Issue by m-a-mohsen** [Gourieff/comfyui-reactor-node#258]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

installation didn't find module named 'folder_paths' , failed to install

### Steps to reproduce the problem

Your workflow
- brew miniconda
- conda env py3.8
- comfyui
- using --cpu
- installed from ui manger

### Sysinfo

MacBook Pro (Retina, 15-inch, Late 2013)
2,3 GHz Quad-Core Intel Core i7
macOS Big Sur 11.7.10

### Relevant console log

```Shell
## ComfyUI-Manager: EXECUTE => ['/usr/local/Caskroom/miniconda/base/envs/pytorch_env/bin/python', 'install.py']
[!] Traceback (most recent call last):
[!]   File "install.py", line 14, in <module>
[!]     from folder_paths import models_dir
[!] ModuleNotFoundError: No module named 'folder_paths'
[!]
[!] During handling of the above exception, another exception occurred:
[!]
[!] Traceback (most recent call last):
[!]   File "install.py", line 17, in <module>
[!]     models_dir = os.path.join(Path(__file__).parents[2], "models")
[!]   File "/usr/local/Caskroom/miniconda/base/envs/pytorch_env/lib/python3.8/pathlib.py", line 621, in __getitem__
[!]     raise IndexError(idx)
[!] IndexError: 2
install script failed: https://github.com/Gourieff/comfyui-reactor-node
```

**Comment by Gourieff** [comment]
The most compatible versions of Python for ComfyUI are 3.10 and 3.11
'folder_paths' is the part of ComfyUI, it should be imported with no issues if everything is ok with the folders structure and env you use
