### ISSUE TITLE
Request - FaceRestoration Only on Swapped Face

### ISSUE THREAD

**Issue by Kinglord** [Gourieff/comfyui-reactor-node#26]
Hello,

I'm using the newest version of the plugin and the improvements are great but are causing me more problems than they have solved. I am trying to replace faces on one person in a crowd, and whenever I use the face restoration feature is applies to all faces it finds in the image, even background faces that are meant to be blurry and out of focus. Obviously I can work around this with some editing, but that's not always possible and takes some time.

I'd like to be able to control what the face restoration applies to, ideally just the replaced face, but if I had some form of control, like being able to set a confidence %, a max number of detected faces, I mean there's a lot of ways to set this up and I'll leave it to you to decide if and when you implement something like this. I think at a high level though, most of us don't want to restore every face that might be present on a multi face image.

That said things are working well on single character images with the exception of eye color but I think that's more a fault with the models than anything else.

**Comment by Gourieff** [comment]
Hello there!

Yes, you're right, that's not a very pleasant thing of the face restoration logic, Codeformer or GFPGAN get a whole image and restore the every face that can be detected
It's implemented like in A1111
In future releases I will try to solve it somehow (via masks or crop+blend), or maybe someone will make a PR
Need to look up if there are some nodes that already can provide smth like an inpainting logic with a mask
We can generate an image -> set a mask of the area with faces we need to swap -> swap them and restore via ReActor -> and then blend them back in the image 🤔

**Comment by Kinglord** [comment]
Thanks for the reply! And I'd love to help more if I could but for now I can just throw you some links in case they help. The most popular and extensive is the [Impact Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack) that has a bunch of masking and inpainting stuff (i use the face detailer all the time). There's an older one i used to use that might be easier to pick apart that does basic face masking and inpainting here - [masquerade pack](https://github.com/BadCafeCode/masquerade-nodes-comfyui).

**Comment by ckao10301** [comment]
Hi @Gourieff I updated the reactor node but am still having this issue. What is the proper workflow to fix this? Mine is like this


![image](https://github.com/user-attachments/assets/3dc3dd6c-b429-42a6-b059-516280f2f0f2)
