### ISSUE TITLE
[Feature]: Replace the largest face in the image....

### ISSUE THREAD

**Issue by nokai** [Gourieff/comfyui-reactor-node#261]
### Feature description

Replace the largest face in the image....
I don't know if it could be done or if it's already done but I haven't found it anywhere. There should be a way to replace the main face of the image (the largest face).
Many times they appear more faces in the image and do not replace the main one.

**Comment by starinskycc** [comment]
I also need it, especially when it comes to video face changing

**Comment by Gourieff** [comment]
Yes, this feature is in the roadmap and will be implemented soon
