### ISSUE TITLE
Installing nukes my comfy UI

### ISSUE THREAD

**Issue by worthy7** [Gourieff/comfyui-reactor-node#262]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I have ComfyUI with the Manager and a bunch of other extensions/models etc all downloaded.

I wanted to try out the workflow from https://openart.ai/workflows/newfoundland_repentant_4/simple-ipadapter-faceid-and-ipadapter-plus-with-face-detailer-and-upscaler-for-repetitive-faces/FoGHQHcUKvEK3JJUtJ9v
But it loads with many missing modules.

### Steps to reproduce the problem

When it loads, some modules were missing. 

```
When loading the graph, the following node types were not found:
InsightFaceLoader
PrepImageForInsightFace
IPAdapterApplyFaceID
IPAdapterApply
Nodes that have failed to load will show as red on the graph.
```

So I ran the Manager "install missing" feature and then rebooted, it says that one module failed to load in the console:

Didn't fix it.

I googled and found this thread "https://www.reddit.com/r/comfyui/comments/1ap31nq/error_occurred_when_executing_insightfaceloader/"

So I ran the git clone for this repo, and restarted comfy UI. I noticed this error in the console.

```

From Bmad Custom Nodes
 Loaded 122 nodes:
  + api nodes (14)
  + simple utility nodes (58)
  + CV nodes (49)
  + color clip ade20k node (1)
 Not loaded:
  * extension dependent nodes
 Problems:
  ! No module named 'custom_nodes.ComfyUI_ADV_CLIP_emb'

```

When I open the workflow, I still have the same errors of missing modules.

### Sysinfo

Windows, python 3.10

### Relevant console log

```Shell
From Bmad Custom Nodes
 Loaded 122 nodes:
  + api nodes (14)
  + simple utility nodes (58)
  + CV nodes (49)
  + color clip ade20k node (1)
 Not loaded:
  * extension dependent nodes
 Problems:
  ! No module named 'custom_nodes.ComfyUI_ADV_CLIP_emb'
```
```


### Additional information

_No response_

**Comment by Gourieff** [comment]
But there's no ReActor Node in the workflow you mentioned to cause any issues

> I googled and found this thread "https://www.reddit.com/r/comfyui/comments/1ap31nq/error_occurred_when_executing_insightfaceloader/"

If you need this repo only to fix the Insightface issue - just follow this solution https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild
