### ISSUE TITLE
Infinite Loop using RestoreFormerPP

### ISSUE THREAD

**Issue by jnc-nj** [Gourieff/comfyui-reactor-node#277]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

When I input a video with 26 frames, the following occurs the `restore - using hashed face - swap` process keeps looping ad infinitum.
I'm not sure if this is a problem with the new version or with the restore model used (im certain the previous version did not have this problem), but in either case it's happening with irregularity. CPU and RAM gets filled up with each cycle to the point where I have to force restart my machine (this might be a separate issue).

### Steps to reproduce the problem

[workflow-26.json](https://github.com/Gourieff/comfyui-reactor-node/files/15011060/workflow-26.json)

As said previously, it's an irregular occurrence (roughly 5% of all runs using the node?).

### Sysinfo

Linux 528659cf7778 6.2.0-39-generic #40-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:18:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

GPU: A100

### Relevant console log

```Shell
[ReActor] 12:01:14 - STATUS - Restoring with RestoreFormer_PP.onnx
[ReActor] 12:01:15 - STATUS - Restoring 1
...
[ReActor] 12:01:15 - STATUS - Restoring 26
[ReActor] 12:01:40 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 12:01:40 - STATUS - Using Hashed Source Face(s) Model...
[ReActor] 12:01:40 - STATUS - (Image 0) Using Hashed Target Face(s) Model...
...
[ReActor] 12:02:09 - STATUS - (Image 25) Using Hashed Target Face(s) Model...
[ReActor] 12:02:09 - STATUS - Swapping 0...
...
[ReActor] 12:02:11 - STATUS - Swapping 25...
[ReActor] 12:02:11 - STATUS - --Done!--
[ReActor] 12:02:12 - STATUS - Restoring with RestoreFormer_PP.onnx
[ReActor] 12:02:13 - STATUS - Restoring 1
...
[ReActor] 12:02:39 - STATUS - Restoring 26
......
```

**Comment by Gourieff** [comment]
And if you use another model but not RestoreFormer_PP - is the processing ok? No loop?

**Comment by jnc-nj** [comment]
> And if you use another model but not RestoreFormer_PP - is the processing ok? No loop?

Yes, I haven't seen any issues with GFPGAN. Once again, I can't be 100% sure, because restoreformerPP doesn't trigger the loop every time -- the vast majority of the time it's fine. 

On a side note, is onnxruntime-gpu==1.15.1 not supported? 
I get the following error:
```
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)
```
Using onnxruntime instead solves the problem, but seems to be using CPU instead of my A100 card.
