### ISSUE TITLE
[Feature]: The reactor lacks the ability to express facial expressions. 

### ISSUE THREAD

**Issue by lifeng5658** [Gourieff/comfyui-reactor-node#278]
### Feature description

The reactor lacks the ability to express facial expressions. The original video has rich expressions, but after face swapping, it becomes very stiff. The eyes do not move, do not blink, and the ability to show expressions is rated at 10 out of 100.

**Comment by Gourieff** [comment]
I think you do smth wrong, there's almost no issues with copying expressions, even rich ones
It's hard to swap (for the inswapper model) only when the reference is shouting with widely opened mouth or with tongue hanging out
