### ISSUE TITLE
The order of the face Indexes  is reversed

### ISSUE THREAD

**Issue by lldacing** [Gourieff/comfyui-reactor-node#282]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

According to the document description and the actual measurement of the old version, the order of input_faces_index and source_faces_index is consistent with the document description, **left->right**. 
After upgrading to the latest version, the order becomes **right->left**

### Steps to reproduce the problem

set index=0, the face on the far right be changed
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/43737696/bf422d26-8775-4387-a268-083774fe99db)

### Sysinfo

windows 11
Total VRAM 4096 MB, total RAM 32406 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16

### Relevant console log

```Shell
[ReActor] 15:35:29 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 15:35:29 - STATUS - Using Hashed Source Face(s) Model...
[ReActor] 15:35:29 - STATUS - Using Hashed Target Face(s) Model...
[ReActor] 15:35:29 - STATUS - Swapping...
[ReActor] 15:35:29 - STATUS - --Done!--
[ReActor] 15:35:29 - STATUS - Restoring with GFPGANv1.4.pth
```

**Comment by Gourieff** [comment]
My fault, forgot to change the description, default order now is "large-small"
You can change this option by adding ReActorFaceSwapOpt + ReActorOptions nodes instead of ReActorFaceSwap

**Comment by bizzou** [comment]
I noticed the same. It is reversed MOST of the time. Not always, though. I did many generations back to back and sometimes the order is changed (back to the correct order). Hope that makes sense and helps finding the bug.

**Comment by Gourieff** [comment]
> I noticed the same. It is reversed MOST of the time. Not always, though. I did many generations back to back and sometimes the order is changed (back to the correct order). Hope that makes sense and helps finding the bug.

But it's not a bug, the answer is in my previous comment, "large->small" is by default now

**Comment by lldacing** [comment]
> My fault, forgot to change the description, default order now is "large-small" You can change this option by adding ReActorFaceSwapOpt + ReActorOptions nodes instead of ReActorFaceSwap
got it, thanks
