### ISSUE TITLE
The first face in the selected order gets restored multiple times when performing multiple face swaps on a single image.

### ISSUE THREAD

**Issue by StellarBeing25** [Gourieff/comfyui-reactor-node#284]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Whenever I try to do a two-person face swap in a single input image, the first face gets restored one more time when the input image passes through the next reactor node for second face swap, due to which the face swapped first become very sharp compared to the face swapped and restored last. Please fix it such that only the faces getting swapped are restored in each reactor node, automatically masking and excluding the other faces. 

[Edit]- Just figured out that this can be fixed by turning off the face restore in the first node and doing all face restore in the second node itself, but you should enable automatic mask and restore to avoid restoration of non-swapped high-resolution faces.

### Steps to reproduce the problem

Your workflow
![Screenshot](https://github.com/Gourieff/comfyui-reactor-node/assets/152368658/7547a0ab-db7a-4f74-a224-0d7d6e263886)

### Sysinfo

OS- Windows 11
Browser- Firefox
GPU- Nvidia RTX 3060

### Relevant console log

```Shell
No Log
```

**Comment by Gourieff** [comment]
You can use concatenate Node if you want to take faces from several images
And another point is when you use GPEN - it can give too much contrast on the resulted face, I recommend to reduce face_restore_visibility for GPEN or use GFPGAN instead or CodeFormer with fidelity > 0.5

![image](https://github.com/Gourieff/comfyui-reactor-node/assets/85128026/9165a6a0-d634-4377-a61c-6134988b3da2)

**Comment by Gourieff** [comment]
But if you really need to swap with separate ReActor nodes with independent masking, just set a simple pipeline of masking nodes and provide two different masks to ReActor Masking Helpers

![image](https://github.com/Gourieff/comfyui-reactor-node/assets/85128026/c72d1b5d-20df-4c22-9eda-37b175a36301)

I don't want to make ReActor too heavy, especially considering the fact that there are a huge amount of different wonderful nodes which can help to solve almost every task in ComfyUI, just use them
