### ISSUE TITLE
Not all the facerestore models are available

### ISSUE THREAD

**Issue by XTRMsavage** [Gourieff/comfyui-reactor-node#286]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I've downloaded all the models from https://huggingface.co/datasets/Gourieff/ReActor/tree/main/models/facerestore_models to \ComfyUI_windows_portable\ComfyUI\models\facerestore_models. But in ComfyUI only these models are visible.
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/90519573/4cbde911-2ccf-44dd-aad1-15ed0930ab9f)
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/90519573/d9d3100f-c755-4309-88e9-66487164ee32)
How to make the other ones available as well? 

### Steps to reproduce the problem

standard workflow. 
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/90519573/8fe3c1e9-d3eb-445f-abd3-058d7513f792)

### Sysinfo

windows 10, chrome, 4090

### Relevant console log

```Shell
n/a
```

**Comment by Gourieff** [comment]
Usually you should just reload the page and new models will appear

**Comment by XTRMsavage** [comment]
> Usually you should just reload the page and new models will appear

Yep, I was hoping the same, but even after countless restarts I am still seeing only 4 models, as I have posted in the op.

**Comment by Gourieff** [comment]
This is very strange, it also can happen if you use the outdated version of ReActor, but I see that you have the Masking Helper node in the workflow 🤔
Try to remove `comfyui-reactor-node` directory and `git clone` the repo again

**Comment by XTRMsavage** [comment]
> This is very strange, it also can happen if you use the outdated version of ReActor, but I see that you have the Masking Helper node in the workflow 🤔 Try to remove `comfyui-reactor-node` directory and `git clone` the repo again

Hi, I have done as said, only in ReActor _ FFS[OPTIONS] node the new models are visible.

**Comment by XTRMsavage** [comment]
> This is very strange, it also can happen if you use the outdated version of ReActor, but I see that you have the Masking Helper node in the workflow 🤔 Try to remove `comfyui-reactor-node` directory and `git clone` the repo again

Do I need to do all this again,

Then install Insightface:
(SD WebUI) pip install insightface-0.7.3-cp310-cp310-win_amd64.whl (for 3.10) or pip install insightface-0.7.3-cp311-cp311-win_amd64.whl (for 3.11) or pip install insightface-0.7.3-cp312-cp312-win_amd64.whl (for 3.12)
(ComfyUI Portable) python_embeded\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl (for 3.10) or python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl (for 3.11) or python_embeded\python.exe -m pip install insightface-0.7.3-cp312-cp312-win_amd64.whl (for 3.12)
