### ISSUE TITLE
comfyui-manager - assert 'detection' in self.models AssertionError

### ISSUE THREAD

**Issue by Amit30swgoh** [Gourieff/comfyui-reactor-node#290]
### First, confirm
by the way ho can i load models why its emepty i downloaded entelope and buffalo_l 
- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

AssertionError 
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/42430868/2bc3e2e5-abf3-4eeb-a824-409189b2ce22)
also no face model ? 
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/42430868/c6d2d6b5-196e-41e4-9093-a31d9d6f9e58)
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/42430868/7412bcb7-a7f8-4bda-9cc3-5d264ef7ba42)
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/42430868/6e203dbc-854d-4379-a1b4-82a624b81f2a)
which file to change to .safetensors? 
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/42430868/19455496-25dd-42e5-bd86-26ce957b206f)
and where to put them please
    assert 'detection' in self.models
AssertionError

### Steps to reproduce the problem

Your workflow

### Sysinfo

assert 'detection' in self.models
AssertionError

### Relevant console log

```Shell
assert 'detection' in self.models
AssertionError
```

**Comment by Amit30swgoh** [comment]
reactortest what is this? 
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/42430868/5bffb2d3-b65c-4780-857f-944800c82a56)

**Comment by Gourieff** [comment]
'test' is just a name for the facemodel file, you can type any name you want
All the models are stored in the `ComfyUI/models/reactor/faces` directory

> assert 'detection' in self.models

Try to re-download the inswapper model and the "buffalo_l" models as well and put them to the `ComfyUI/models/insightface` directory replacing existing files
You can download models from here: https://huggingface.co/datasets/Gourieff/ReActor/tree/main/models
