### ISSUE TITLE
[SOLVED] Missing module  Cython

### ISSUE THREAD

**Issue by lvalics** [Gourieff/comfyui-reactor-node#296]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

On installation I had this error, Cython missing. I added to requirements.txt and the installer gone through.

### Steps to reproduce the problem

Your workflow
Installing the module.

### Sysinfo

Windows 11.

### Relevant console log

```Shell
none now.
```

**Comment by largekhosro** [comment]
Same issue 
 ModuleNotFoundError: No module named 'Cython'

**Comment by cbccbd** [comment]
Same issue

**Comment by Gourieff** [comment]
https://github.com/Gourieff/comfyui-reactor-node/issues/154

**Comment by sechina** [comment]
> #154
> 
> https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

thank you!
