### ISSUE TITLE
The reactor node cannot process images that do not contain faces.

### ISSUE THREAD

**Issue by kobevv5** [Gourieff/comfyui-reactor-node#304]
### Feature description

The effect is great, thank you  for his efforts.   A Feature suggestion: 
When using the reactor node to process a video, if the video contains partial non-face images, although the results can be returned normally, the output will only include images with detected faces, and images with no faces detected will be filtered out, resulting in an inconsistent number of input images and output images. I would like to suggest: should the number of input/output pictures of the reactor node be the same? That is, the picture where the face is detected can replace the face normally, pictures without faces detected can also be output normally, but just no processing is performed. 

Reactor_masking has the same suggestion too.

Thx a lot

**Comment by Rvage0815** [comment]
i noticed the same issue, its a mess and took a while to find this "mistake" cuz i thought the frame interpolation is doin wrong. what makes you think that it would be a good idea to simply remove images that have not been changed from the batch? seriously wtf, this is the same garbage you find in grounding dino. only outputting images where the recognition was successful. please fix that.

**Comment by DonBaronFactory** [comment]
https://github.com/Gourieff/comfyui-reactor-node/issues/288

**Comment by Gourieff** [comment]
It's fixed in the Evolve branch, I will merge it soon into Main

**Comment by Gourieff** [comment]
Merged
