### ISSUE TITLE
local variable 'face_segment' referenced before assignment

### ISSUE THREAD

**Issue by kobevv5** [Gourieff/comfyui-reactor-node#306]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

In comfyui-reactor-node/nodes.py,  when the program returns at line 864 (excute "continue") , but the local variable 'face_segment' is not defined  at this moment, it will cause the program to exit abnormally.

### Steps to reproduce the problem

no

### Sysinfo

linux redhat

### Relevant console log

```Shell
File "/data/wq/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/wq/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/wq/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data/wq/ComfyUI/custom_nodes/comfyui-reactor-node/nodes.py", line 941, in execute
    return (result,combined_mask,mask_image_final,face_segment,)
UnboundLocalError: local variable 'face_segment' referenced before assignment
```

**Comment by Gourieff** [comment]
Please update ReActor to the latest version
