### ISSUE TITLE
Hands over face? Its a bug or thats correct? How to get around this?

### ISSUE THREAD

**Issue by dociinhohot** [Gourieff/comfyui-reactor-node#311]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

The face always appears to be trying to overlap on top of the hands... This was the best configuration I could find to minimize the problem, but I still have it, especially in videos where the face moves a lot or something is on top of the face. Does anyone know ways to get around this? Or just with a mask edit in AE/Premier? Which is what I'm doing for now.

![image](https://github.com/Gourieff/comfyui-reactor-node/assets/134243556/004b000f-fe69-4392-b305-381247b94cc7)
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/134243556/ac1b696c-6d5a-4387-828c-b0b26965faec)
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/134243556/f92be619-1520-43f2-866a-5d1e655f69f5)

### Steps to reproduce the problem

Only using the node reactor

### Sysinfo

Windows 11
RTX 2080 Super

### Relevant console log

```Shell
No issues
```

**Comment by Gourieff** [comment]
Try to use "vit_l" Sam model instead of "vit_b" with the Masking Helper node
https://huggingface.co/datasets/Gourieff/ReActor/tree/main/models/sams
"vit_l" helps with occlusion

**Comment by dociinhohot** [comment]
> Try to use "vit_l" Sam model instead of "vit_b" with the Masking Helper node https://huggingface.co/datasets/Gourieff/ReActor/tree/main/models/sams "vit_l" helps with occlusion

Thanks for the reply. How could I be using the mask helper node in a video? I didn't quite understand how to use it. I put output video directly in image on masking helper node and put the output of reactor  fast face swap node in the input swapped_image on reactor masking helper node? Correct?
