### ISSUE TITLE
[SOLVED] An error occurred after updating the latest version

### ISSUE THREAD

**Issue by waynechan028** [Gourieff/comfyui-reactor-node#33]
got prompt
Failed to validate prompt for output 58:
* ReActorFaceSwap 62:
  - Required input is missing: source_image
Output will be ignored

**Comment by Gourieff** [comment]
Please read the doc https://github.com/Gourieff/comfyui-reactor-node#note

**Comment by waynechan028** [comment]
> 请阅读文档https://github.com/Gourieff/comfyui-reactor-node#note

Error resolved, thank you very much!
