### ISSUE TITLE
Why do I not have 'Main Nodes' in my 'reactor'?

### ISSUE THREAD

**Issue by EnlightenedAI** [Gourieff/comfyui-reactor-node#334]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Why do I not have 'Main Nodes' in my 'reactor'?

### Steps to reproduce the problem

Why do I not have 'Main Nodes' in my 'reactor'?

### Sysinfo

Why do I not have 'Main Nodes' in my 'reactor'?

### Relevant console log

```Shell
Why do I not have 'Main Nodes' in my 'reactor'?
```

**Comment by Gourieff** [comment]
Please provide your Console log

**Comment by EnlightenedAI** [comment]
This problem has been resolved.
