### ISSUE TITLE
recently the results are in BAD QUALITY !!!???

### ISSUE THREAD

**Issue by XTRMsavage** [Gourieff/comfyui-reactor-node#336]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

HI I am experiencing this drop in quality, the original is 736 x 1104. When I do faceswap the quality is very poor. Why is this?

### Steps to reproduce the problem

Your workflow
<img width="1711" alt="image" src="https://github.com/Gourieff/comfyui-reactor-node/assets/90519573/b9248f00-3e80-4f63-96f9-57cc7cb49125">

### Sysinfo

chrome, 4090, windows 10

### Relevant console log

```Shell
n/a
```

**Comment by wcde** [comment]
@XTRMsavage, this is due to buggy blending. The higher target resolution, the worse quality of swap. Only way to avoid bugs with it is to use target image smaller than face-swap model output.

**Comment by Abhijeetisilanos** [comment]
use methode given in this website, use xformer which suitable to your cuda 
https://civitai.com/articles/5315/install-docopt-insightface-facexlib-onnx-gpu-cuda-118
