### ISSUE TITLE
ModuleNotFoundError: No module named 'insightface'

### ISSUE THREAD

**Issue by SidiusAdventures** [Gourieff/comfyui-reactor-node#344]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

insightface is failing to import so i'm doing the trouble shooting steps i'm on python version 3.11.8 so i'm using the 3.11 version of the download i the troubleshooting steps but once i get to the final part i get this error: G:\AI\ComfyUI\ComfyUI_windows_portable>pip install insightface-0.7.3-cp311-cp311-win_amd64.whl
ERROR: insightface-0.7.3-cp311-cp311-win_amd64.whl is not a supported wheel on this platform.

i've reinstalled reactor in comfy ui a few times now and insightface always fails i even made sure i got visual studio 2022
so i'm quite stumped on where to continue if its a known bug i guess i'll just have to wait for a bugfix?

### Steps to reproduce the problem

just installing reactor via comfy ui manager seems to reproduce this bug and from what i've seen on the open requests its a bug going around

### Sysinfo

Import times for custom nodes:
   0.0 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
   0.0 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.0 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.3 seconds (IMPORT FAILED): G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.3 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.6 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.9 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   1.6 seconds: G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

OS: Windows 11
Browser: Brave
GPU: Nvidia Geforce 2060 Super

### Relevant console log

```Shell
## Execute install/(de)activation script for 'G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node'
 Collecting insightface==0.7.3
   Using cached insightface-0.7.3.tar.gz (439 kB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [18 lines of output]
[!]   Traceback (most recent call last):
[!]     File "G:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]       main()
[!]     File "G:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "G:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]       return hook(config_settings)
[!]              ^^^^^^^^^^^^^^^^^^^^^
[!]     File "G:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
[!]       return self._get_build_requires(config_settings, requirements=['wheel'])
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "G:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
[!]       self.run_setup()
[!]     File "G:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
[!]       exec(code, locals())
[!]     File "<string>", line 11, in <module>
[!]   ModuleNotFoundError: No module named 'Cython'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
[!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
[!]
[!] [notice] A new release of pip is available: 24.0 -> 24.1.1
[!] [notice] To update, run: G:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
 CUDA 12.1
 Status: The 'insightface==0.7.3' distribution was not found and is required by the application
 Ok


Traceback (most recent call last):
  File "G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1890, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "G:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'
```

**Comment by Hunt3rseeker** [comment]
I'm having a similar problem. Insightface seems to be downloaded in models, and the reactor folder is in it's right place with the right files. I tried both manually installing it and via comfy-manager, both failed to install successfully. 
The first log is from installing it manually, and the second is from installing it through comfy-manager.

![image](https://github.com/Gourieff/comfyui-reactor-node/assets/98604770/6922085f-3472-4871-b82f-5b11444f13a5)



`16:21:58.549 [Init] === StableSwarmUI v0.6.4.1 Starting at 2024-06-30 16:21:58 ===                                                                                                                                                           16:21:58.582 [Init] Prepping extension: StableSwarmUI.Builtin_StabilityAPIExtension.StabilityAPIExtension...                                                                                                                                 16:21:58.589 [Init] Prepping extension: StableSwarmUI.Builtin_ScorersExtension.ScorersExtension...                                                                                                                                           16:21:58.590 [Init] Prepping extension: StableSwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...                                                                                                                             16:21:58.590 [Init] Prepping extension: StableSwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...                                                                                                                               16:21:58.591 [Init] Prepping extension: StableSwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...                                                                                                                            16:21:58.591 [Init] Prepping extension: StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...                                                                                                                                      16:21:58.592 [Init] Prepping extension: StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...                                                                                                                                16:21:58.621 [Init] Parsing command line...                                                                                                                                                                                                  16:21:58.621 [Init] Loading settings file...                                                                                                                                                                                                 16:21:58.641 [Init] Re-saving settings file...                                                                                                                                                                                               16:21:58.657 [Init] Applying command line settings...                                                                                                                                                                                        16:21:58.680 [Init] Prepping options...                                                                                                                                                                                                      16:21:58.705 [Init] Current git commit marked as date 2024-06-21 09:26:07                                                                                                                                                                    16:21:58.741 [Init] Swarm is up to date! Version 0.6.4.1 is the latest.                                                                                                                                                                      16:21:58.770 [Init] CPU Cores: 16 | RAM: 31.91 GiB total, 25.30 GiB available                                                                                                                                                                16:21:58.770 [Init] GPU 0: NVIDIA GeForce RTX 3070 Ti | Temp 44C | Util 45% GPU, 37% Memory | VRAM 8.00 GiB total, 7.17 GiB free, 675.00 MiB used                                                                                            16:21:58.802 [Init] Loading models list...                                                                                                                                                                                                   16:21:59.173 [Init] Loading backends...                                                                                                                                                                                                      16:21:59.174 [Init] Loading backends from file...                                                                                                                                                                                            16:21:59.178 [Init] Initializing backend #0 - ComfyUI Self-Starting...                                                                                                                                                                       16:21:59.178 [Init] Prepping API...                                                                                                                                                                                                          16:21:59.179 [Init] Backend request handler loop ready...                                                                                                                                                                                    16:21:59.180 [Init] Prepping webserver...                                                                                                                                                                                                    16:21:59.317 [Init] Scan for web extensions...                                                                                                                                                                                               16:21:59.319 [Init] Readying extensions for launch...                                                                                                                                                                                        16:21:59.320 [Init] Launching server...                                                                                                                                                                                                      16:21:59.320 [Init] Starting webserver on http://localhost:7801                                                                                                                                                                              16:21:59.350 [Init] Program is running.                                                                                                                                                                                                      16:21:59.770 [Info] Self-Start ComfyUI (Git Pull) exited properly.                                                                                                                                                                           16:21:59.775 [Info] Self-Start comfy node pull (ComfyUI-SAI_API) exited properly.                                                                                                                                                            16:21:59.783 [Info] Self-Start comfy node pull (sd-dynamic-thresholding) exited properly.                                                                                                                                                    16:22:00.384 [Info] Self-Start comfy node pull (sd-dynamic-thresholding) exited properly.                                                                                                                                                    16:22:00.385 [Info] Self-Start comfy node pull (comfyui_controlnet_aux) exited properly.                                                                                                                                                     16:22:00.406 [Info] Self-Start comfy node pull (ComfyUI-SAI_API) exited properly.                                                                                                                                                            16:22:00.414 [Init] Self-Start ComfyUI-0 on port 7821 is loading...                                                                                                                                                                          16:22:04.609 [Info] Creating new admin session 'local' for ::1                                                                                                                                                                               16:22:16.846 [Warning] ComfyUI-0 on port 7821 stderr: [!]   error: subprocess-exited-with-error                                                                                                                                              16:22:16.847 [Warning] ComfyUI-0 on port 7821 stderr: [!]                                                                                                                                                                                    16:22:16.848 [Warning] ComfyUI-0 on port 7821 stderr: [!]   ModuleNotFoundError: No module named 'Cython'                                                                                                                                    16:22:16.848 [Warning] ComfyUI-0 on port 7821 stderr: [!]   [end of output]                                                                                                                                                                  16:22:16.849 [Warning] ComfyUI-0 on port 7821 stderr: [!] error: subprocess-exited-with-error                                                                                                                                                16:22:16.849 [Warning] ComfyUI-0 on port 7821 stderr: [!]                                                                                                                                                                                    16:22:34.384 [Warning] ComfyUI-0 on port 7821 stderr: [!]   error: subprocess-exited-with-error                                                                                                                                              16:22:34.385 [Warning] ComfyUI-0 on port 7821 stderr: [!]                                                                                                                                                                                    16:22:34.386 [Warning] ComfyUI-0 on port 7821 stderr: [!]   ModuleNotFoundError: No module named 'Cython'                                                                                                                                    16:22:34.387 [Warning] ComfyUI-0 on port 7821 stderr: [!]   [end of output]                                                                                                                                                                  16:22:34.388 [Warning] ComfyUI-0 on port 7821 stderr: [!] error: subprocess-exited-with-error                                                                                                                                                16:22:34.388 [Warning] ComfyUI-0 on port 7821 stderr: [!]                                                                                                                                                                                    16:22:41.715 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):                                                                                                                                                     16:22:41.716 [Warning] ComfyUI-0 on port 7821 stderr:   File "C:\Ai_Root\SD.Swarm\dlbackend\comfy\ComfyUI\nodes.py", line 1906, in load_custom_node                                                                                          16:22:41.716 [Warning] ComfyUI-0 on port 7821 stderr:     module_spec.loader.exec_module(module)                                                                                                                                             16:22:41.717 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module                                                                                                              16:22:41.718 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                                                                                         16:22:41.718 [Warning] ComfyUI-0 on port 7821 stderr:   File "C:\Ai_Root\SD.Swarm\dlbackend\comfy\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>                                                               16:22:41.719 [Warning] ComfyUI-0 on port 7821 stderr:     from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS                                                                                                                 16:22:41.719 [Warning] ComfyUI-0 on port 7821 stderr:   File "C:\Ai_Root\SD.Swarm\dlbackend\comfy\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>                                                                  16:22:41.720 [Warning] ComfyUI-0 on port 7821 stderr:     from insightface.app.common import Face                                                                                                                                            16:22:41.721 [Warning] ComfyUI-0 on port 7821 stderr: ModuleNotFoundError: No module named 'insightface'                                                                                                                                     16:22:41.721 [Warning] ComfyUI-0 on port 7821 stderr:                                                                                                                                                                                        16:22:46.420 [Init] Self-Start ComfyUI-0 on port 7821 started. `
`C:\Users\Jespe>cython --version
Cython version 3.0.10 `

**Comment by imanshirani** [comment]
1- You should choose the InsightFace version from your python
For example, my python was 3.11.8  I downloaded "insightface-0.7.3-cp311-cp311-win_amd64.whl" and copy on Root comfyUI

|-- ComfyUI
|---  insightface-0.7.3-cp311-cp311-win_amd64.whl

2 - open a terminal in ComfyUI root and type the code
`.\python_embeded\python.exe -m pip install "your path \insightface-0.7.3-cp311-cp311-win_amd64.whl" onnxruntime`

![Screenshot 2024-07-01 221557](https://github.com/Gourieff/comfyui-reactor-node/assets/16049924/100cef59-1f44-4a35-ba3e-25c0edf57837)

**Comment by Slowpoke70** [comment]
I had to add -user to this command due to permissions.

**Comment by zhuwentao2150** [comment]
I'm confused. I followed these steps, but still got an error.

![20240821172724_000049_管理员_ C__Windows_System32_cmd exe](https://github.com/user-attachments/assets/53b11124-3115-4a49-a74a-935edd8f0ff1)

**Comment by Gourieff** [comment]
@zhuwentao2150 you should use another version of insightface package for your ComfyUI build
Check `python_embeded\python.exe -V` and download the package according this version
