### ISSUE TITLE
Facerestores other than GPEN 2048/1024 do not work anymore after toggling faceboost, failed inference

### ISSUE THREAD

**Issue by Mozoloa** [Gourieff/comfyui-reactor-node#346]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Usual workflow utilizing facerestore at the node level won't work with 512 anymore after toggling face boost, doing a few gens, then turning it off

Codeformer
`Failed inference: The size of tensor a (4096) must match the size of tensor b (256) at non-singleton dimension 0`

GPEN 512
`Failed inference: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input for the following indices`

### Steps to reproduce the problem

Create a workflow using faceboost, use different models then turn faceboost off, now the lower res models won't work anymore

### Sysinfo

Windows 11
Brave
4090

### Relevant console log

```Shell
Codeformer
`Failed inference: The size of tensor a (4096) must match the size of tensor b (256) at non-singleton dimension 0`

GPEN 512
`Failed inference: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input for the following indices`
```

**Comment by Gourieff** [comment]
Fixed https://github.com/Gourieff/comfyui-reactor-node/commit/785e93d5e0a7db4832f066504fba48fc57ec6c7c
