### ISSUE TITLE
Reactor Custom Node Causes Issues with other Custom Nodes using ComfyUI Standalone (Impact Pack / Controlnetaux / Promptgenerator)

### ISSUE THREAD

**Issue by Kinglord** [Gourieff/comfyui-reactor-node#35]
I was trying to solve an issue that cropped up suddenly for me with some odd protobuf error when using some Impact Pact nodes and a prompt generator custom node. After digging into it I'm pretty sure the issue is the same that a ROOP node was causing which has to do with double loading protobuf with non-venv installs, and the order that things are loaded. I'm pretty sure it's the same issue as this one here:

https://github.com/Fannovel16/comfy_controlnet_preprocessors/issues/70
https://github.com/ssitu/ComfyUI_roop/issues/1

There is some underlying issue here I think that is going to keep cropping up depending on install or execution order. I'm not sure if there's a way to check and not reload protobuf, I did find one posted ComfyUI hack to force it to load the node last but that's not ideal. Hopefully there's an easy fix that can be done for the init file. If posting the actual errors or any part of my configuration would help at all I'm happy to do so. I also understand this isn't a problem for everyone since it only hits standalone users and not venv ones (AFAIK).

I know the old controlnet nodes for ComfyUI were causing an issue with this, I think he fixed them with the new controlnet_aux project so maybe the same fix could apply? Just hoping :D

**Comment by jencoughlin** [comment]
I have the standalone ComfyUI and it won't work for me either!

**Comment by storyicon** [comment]
I have another magic that may help you solve this problem.
Add the following code to the header of the `main.py` file in the comfyui root directory (like: [main.py#L1](https://github.com/comfyanonymous/ComfyUI/blob/master/main.py#L1))

```
import onnx
from google.protobuf import reflection
```

Then restart ComfyUI. Maybe you can see something different.
