### ISSUE TITLE
Fast Face Swap node missing face boost input

### ISSUE THREAD

**Issue by XTRMsavage** [Gourieff/comfyui-reactor-node#355]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

![image](https://github.com/Gourieff/comfyui-reactor-node/assets/90519573/2a731c52-42c3-4028-a549-127bb848913b)
I did a git pull inside `\custom_nodes\comfyui-reactor-node` but the nodes haven't been updated. Do I need to update ComfyUI as well?

### Steps to reproduce the problem

![image](https://github.com/Gourieff/comfyui-reactor-node/assets/90519573/5f4785f9-5fae-466c-99b4-1f6916e9e330)

### Sysinfo

chrome, windows 10

### Relevant console log

```Shell
n/a
```

**Comment by Gourieff** [comment]
Just try to reload the page, delete the node and add it again to your pipeline
