### ISSUE TITLE
(IMPORT FAILED) ReActor Node for ComfyUI

### ISSUE THREAD

**Issue by eotamis** [Gourieff/comfyui-reactor-node#369]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I have not figured out the very reason why reactor node would fail to load giving an "import failed" remark and an option to fix it in the custom nodes manager. I try this and it works until I quit comfy ui and restart it.

### Steps to reproduce the problem

Your workflow
I have followed every step of the git page references going through insight face installation (looks like installation was somehow correct since manager lets me fix it until a restart).

I am getting below errors when I restart comfy ui when I restart the server. Please any help is appreciated.

### Sysinfo

Win 11, rtx3070ti mobile

### Relevant console log

```Shell
Traceback (most recent call last):
File "C:\Users\eo_dummy\Documents\GEN_AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1931, in load_custom_node
module_spec.loader.exec_module(module)
File "", line 940, in exec_module
File "", line 241, in call_with_frames_removed
File "C:\Users\eo_dummy\Documents\GEN_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node_init.py", line 23, in
from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
File "C:\Users\eo_dummy\Documents\GEN_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in
from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

Cannot import C:\Users\eo_dummy\Documents\GEN_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\eo_dummy\Documents\GEN_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
C:\Users\eo_dummy\Documents\GEN_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
```

**Comment by ostap667inbox** [comment]
same

**Comment by Gourieff** [comment]
https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

https://github.com/Gourieff/comfyui-reactor-node/issues?q=is%3Aissue+is%3Aclosed+No+module+named+%27insightface%27

**Comment by curious-george-is-available** [comment]
I'm trying to deploy a comfy workflow to Baseten Serverless Inference and I'm getting the error
Cannot import /app/ComfyUI/custom_nodes/comfyui-reactor-node module for custom nodes: No module named 'insightface'

Can please someone guide me? non-coder here

**Comment by curious-george-is-available** [comment]
> I'm trying to deploy a comfy workflow to Baseten Serverless Inference and I'm getting the error Cannot import /app/ComfyUI/custom_nodes/comfyui-reactor-node module for custom nodes: No module named 'insightface'
> 
> Can please someone guide me? non-coder here

@Gourieff

**Comment by kwang0429** [comment]
same problem as well.

**Comment by miguelgargallo** [comment]
same problem here

**Comment by ZIX9900TOYOU** [comment]
did anyone fixed it?

**Comment by braddave** [comment]
I did but after something update, this problem come back. I was so hurry for work and stupid, not wrote down somewhere and nor share :(
