### ISSUE TITLE
Multi Images passing but getting single output

### ISSUE THREAD

**Issue by developer-kliky-app** [Gourieff/comfyui-reactor-node#377]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### Can you help me?

Getting wong output.

Passing image list as a input [image1, image2, image3,  image4] images
source is multi index but passing only [3] or any index

Output should be [output_image1, output_image2, output_image3,  output_image4]  but getting single image only

![Screenshot from 2024-07-28 17-28-34](https://github.com/user-attachments/assets/45824b02-ce5f-4c19-8dd2-2a1090b1613d)

### Steps to reproduce the problem

Passing image list as a input [image1, image2, image3,  image4] images
source is multi index but passing only [3] or any index

Output should be [output_image1, output_image2, output_image3,  output_image4]  but getting single image only

### Sysinfo

Ubuntu, 48GB GPU

### Relevant console log

```Shell
No Error Occured! Somethings is missing?
```

**Comment by Gourieff** [comment]
Try to convert List to Batch
