### ISSUE TITLE
Troubles reinstalling Reactor node

### ISSUE THREAD

**Issue by ryuujtyh** [Gourieff/comfyui-reactor-node#39]
I had to delete the extension because the node stopped appearing in Comfyui.
When it comes to reinstalling it, there is no way for the folder in which the models are supposed to be installed to appear: facerestore_models. I have the insightface one but not the other one. And if I create it and add the models, the node still does not appear. I get this error: "Unable to import dependency onnxruntime." And also Cannot import C:\Users\Rure\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: Unable to import dependency onnxruntime

**Comment by Gourieff** [comment]
Do you use ComfyUI Manager?
If don't - try to run `install.bat` from the `comfyui-reactor-node` folder

**Comment by ryuujtyh** [comment]
I have tried both ways. From the Comfyui manager program it does not create that folder for me and it does not appear in the node either. 

I have already run the .bat. I did it again and this appears:

"Installing...
Installing...
Error: expected string or bytes-like object
Requirement already satisfied: numpy in..."

"Error: expected string or bytes-like object
Requirement already satisfied: torch in..."

"Error: expected string or bytes-like object
Requirement already satisfied: torchvision in..."

And this:
"DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063"

**Comment by ryuujtyh** [comment]
But what I don't understand is how it worked before and now it doesn't.

**Comment by Gourieff** [comment]
Smth wrong with your python enclosure inside ComfyUI
Did you try `python_embeded\python.exe -m pip install -U pip` ?
Or maybe `python_embeded\python.exe -m pip uninstall -y setuptools` and install setuptools again `python_embeded\python.exe -m pip install setuptools`
