### ISSUE TITLE
Exception during processing - windows version (not portable)

### ISSUE THREAD

**Issue by zejacky** [Gourieff/comfyui-reactor-node#41]
Dear developers, tinkerers and tech people

Yesterday I was messing around with faceFusion, and im almost sure I broke something regarding to opencv or onnxruntime
Not using **venv** :-(  
- opencv-python==4.8.0.76
- pip uninstall onnxruntime onnxruntime-gpu
- pip install onnxruntime-gpu==1.15.1

**Now I have following error:**
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

**What I already did :**
- New clone of ComfyUI
- New clone of reactor-node
- pip uninstall opencv-python==4.8.0.76
- pip install opencv-python==4.7.0.72
- pip install -r requirements.txt- 
- pip uninstall onnxruntime
- pip install onnxruntime-gpu
- reinstall reactor node via Manager
- Cuda deinstall
- Remove PATH variables:
- CUDA_HOME == C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\ 	
- CUDA_PATH == C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\ 	
- CUDA_V11_8 == C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\
- Reboot PC

Still the same error.

Can any of you help me out? 
I would be very happy to use the cool node again without reinstalling windows.

Kr
Jack

**Comment by Gourieff** [comment]
> Dear developers, tinkerers and tech people
> 
> Yesterday I was messing around with faceFusion, and im almost sure I broke something regarding to opencv or onnxruntime Not using **venv** :-(
> 
>     * opencv-python==4.8.0.76
> 
>     * pip uninstall onnxruntime onnxruntime-gpu
> 
>     * pip install onnxruntime-gpu==1.15.1
> 

Hello there!

Instead of `pip install onnxruntime-gpu==1.15.1` you should have run `pip install onnxruntime==1.15.1`
So try once again to uninstall `pip uninstall onnxruntime-gpu` and then install "onnxruntime==1.15.1"

**Comment by zejacky** [comment]
> pip install onnxruntime-gpu==1.15.1

Amazing, it works again. Thank you very much! 

Now I have seen my mistake.

I have executed it as you wrote:
pip uninstall onnxruntime-gpu
pip install onnxruntime==1.15.1

Output:
Installing collected packages: onnxruntime
  Attempting uninstall: onnxruntime
    _Found existing installation: onnxruntime 1.16.0
    Uninstalling onnxruntime-1.16.0:_
      Successfully uninstalled onnxruntime-1.16.0
Successfully installed onnxruntime-1.15.1

**Comment by ffdown** [comment]
> Instead of `pip install onnxruntime-gpu==1.15.1` you should have run `pip install onnxruntime==1.15.1`
> So try once again to uninstall `pip uninstall onnxruntime-gpu` and then install "onnxruntime==1.15.1"

ERROR: Could not install packages due to an OSError: [WinError 5] Отказано в доступе: 'e:\\anaconda3\\lib\\site-packages\\onnxruntime\\capi\\onnxruntime_providers_shared.dll'
Consider using the `--user` option or check the permissions.

**Comment by bihailantian655** [comment]
here   is   my   pip list      still  get this error 

onnx                              1.15.0
onnxruntime                       1.16.1
onnxruntime-gpu                   1.15.1
