### ISSUE TITLE
torch2.4.1+cu124 error

### ISSUE THREAD

**Issue by lesteryebin** [Gourieff/comfyui-reactor-node#438]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

# ComfyUI Error Report
## Error Details
- **Node Type:** ReActorFaceSwap
- **Exception Type:** RuntimeError
- **Exception Message:** D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

### Steps to reproduce the problem

Simply using the reactor node

### Sysinfo

windows10、chrome、torch2.4.1+cu124

### Relevant console log

```Shell
# ComfyUI Error Report
## Error Details
- **Node Type:** ReActorFaceSwap
- **Exception Type:** RuntimeError
- **Exception Message:** D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
```

**Comment by Gourieff** [comment]
> windows10、chrome、torch2.4.1+cu124

Try to downgrade to torch2.3.1+cu121

**Comment by markAking** [comment]
I had the same issue. CUDA 12.4, The issue is with **onnxruntime**. 
I updated onnxruntime-gpu to 1.18.1 but you have to update onnxruntime also! 
`pip uninstall onnxruntime`
`pip install onnxruntime`

it will update onnxruntime to 1.19.2.
Works perfectly afterwords.

**Comment by lesteryebin** [comment]
> 我遇到了同样的问题。CUDA 12.4，问题出在**onnxruntime**上。 更新到 CUDA 12.1 或 12.4 后，**onnxruntime-gpu** 会更新 到 1.18.1， 但您还必须更新**onnxruntime**！******** `pip uninstall onnxruntime` `pip install onnxruntime`
> 
> 它将更新 onnxruntime 到 1.19.2，之后就可以完美运行了。

Thank you for your reply. My onnxruntime has always been 1.19.2. The problem occurred after I updated all the day before yesterday.
