### ISSUE TITLE
[SOLVED] Not compatible with ControlNet pre-processor

### ISSUE THREAD

**Issue by daintyoracle** [Gourieff/comfyui-reactor-node#45]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

This custom node is currently not compatible with ControlNet pre-processor and this custom node will take precedence over control net processors. If you installed this together with controlnet pre-processor node, the control net pre-processor node will dissapear when you restarted comfy UI.

### Steps to reproduce the problem

Install control net pre-processor node over this custom node (vice versa)

### Sysinfo

NVIDIA 1050Ti Mobile
4GB Vram

### Relevant console log

```Shell
N/A
```

**Comment by Gourieff** [comment]
Yes, known issue, not my fault, dependencies conflict
I don't know why but ReActor Node can work with the latest OpenCV library but Controlnet Preprocessor Node cannot at the same time (despite it has opencv-python>=4.8 in requirements)
I think there's a strange bug in opencv-python v4.8.0.76 that causes this behavior

So, to resolve it - try the following:
1. Close ComfyUI if it runs
2. Go to the `ComfyUI\custom_nodes\comfyui_controlnet_aux` folder and edit `requirements.txt`
- change `opencv-python>=4.8.0` to `opencv-python>=4.7.0.72`
3. Go to the ComfyUI root folder, open CMD there and run:
- `python_embeded\python.exe -m pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless`
- `python_embeded\python.exe -m pip install opencv-python==4.7.0.72`

That's it

![изображение](https://github.com/Gourieff/comfyui-reactor-node/assets/85128026/a304ccc8-bd59-4a39-9121-13118b3cf189)

Both extensions works perfectly together
