### ISSUE TITLE
is there a solution for this  edges of the shallow depth agged?

### ISSUE THREAD

**Issue by jasoncow007** [Gourieff/comfyui-reactor-node#451]
### Feature description

![Screenshot_20241009_233340_com_hihonor_photos_SlotAlbumActivity_edit_362077206928179](https://github.com/user-attachments/assets/1eb2e5eb-5ced-4364-b5db-0ef38d553516)
 I tried I tried tunning, but it failed

**Comment by Gourieff** [comment]
Just use it with `ReActorMaskHelper` node with the params as shown here:
https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#050-alpha1
You can use `vit_b` or `vit_l` SAM models (vit_l gives more occlusion)

**Comment by jasoncow007** [comment]
> Just use it with `ReActorMaskHelper` node with the params as shown here:
> https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#050-alpha1
> You can use `vit_b` or `vit_l` SAM models (vit_l gives more occlusion)
> 

thanks for your guidance, I got another problem its about the Ghosting!
[Screenshot_20241011_151028_com_hihonor_photos_SlotAlbumActivity.jpg](https://github.com/user-attachments/assets/34ca2b0c-e462-498a-9852-32d0cbf19829)

**Comment by Gourieff** [comment]
> > Just use it with `ReActorMaskHelper` node with the params as shown here:
> > https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#050-alpha1
> > You can use `vit_b` or `vit_l` SAM models (vit_l gives more occlusion)
> 
> thanks for your guidance, I got another problem its about the Ghosting! [Screenshot_20241011_151028_com_hihonor_photos_SlotAlbumActivity.jpg](https://github.com/user-attachments/assets/34ca2b0c-e462-498a-9852-32d0cbf19829)

To avoid ghosting you should play with ReActorMaskHelper parameters such as "morphology_operation" and "morphology_distance"
