### ISSUE TITLE
Put naistyles.csv on Customnodes_NAI_mod.

### ISSUE THREAD

**Issue by iamanojkumar** [Gourieff/comfyui-reactor-node#458]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

No Matter what I do I could not clear this error. I want to use this node 
I tried creating a dummy file in the location that didn't work
I tried to copy-paste the files under Customnode-universal styles to the NAI folder, but that didn't work either 
I changed a script that had the path to custom-NAI-mod to Custom-universal-mod it also didn't work 

can someone help me to fix this? I really appreciate any help you can provide.

### Steps to reproduce the problem

Your workflow
You can download and use the node if it runs without any issue you can share your custom nodes NAI and universal style folder so I can get an idea of what is going wrong 

### Sysinfo

I'm using Windows 11, Edge browser 

### Relevant console log

```Shell
put the naistyles.csv on the Customnodes_NAI_mod
```

**Comment by anishkumar92** [comment]
I am also facing the same issue

**Comment by Lyyyyyy0625** [comment]
me too

**Comment by zhilioo7** [comment]
我也是

**Comment by zhilioo7** [comment]
我也是

**Comment by zhilioo7** [comment]
我也面临同样的问题

**Comment by joramirez764** [comment]
Yo también me enfrento al mismo problema. 

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: D:\pinokio\api\comfy.git\app

**Comment by Maikhool** [comment]
![image](https://github.com/user-attachments/assets/94427f84-ae1e-4c77-88ca-f4d2a2efc9a7)
It doesn't even make sense for it to be called this many times. Slowing down every single run because it's calling this. What is even going on?

**Comment by salgianna** [comment]
me too!  Mac studio
