### ISSUE TITLE
I know this has been covered many, many times but I can't find the answer - only links upon links 

### ISSUE THREAD

**Issue by offmybach** [Gourieff/comfyui-reactor-node#459]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

ImportError: cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)  
I have re-installed and forced re-install 10x and still not working. I installed manually and read all of instructions. even asked good old gpt4o and still stuck. Please help! Also watched several youtube videos

### Steps to reproduce the problem

Your workflow
loading comfyui portable 

### Sysinfo

windows using comfyui portable build  everything has been updated  nvidia 3070ti

### Relevant console log

```Shell
ImportError: cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)
```

**Comment by Gourieff** [comment]
Did you try to follow closed issues? https://github.com/Gourieff/comfyui-reactor-node/issues?q=is%3Aissue+is%3Aclosed+insightface.thirdparty.face3d.mesh.cython
Or install Insightface whl from these steps https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild
