### ISSUE TITLE
Can't install - installer keeps pulling latest version of numpy and onnxruntime but they aren't compatible

### ISSUE THREAD

**Issue by roundtreetop** [Gourieff/comfyui-reactor-node#505]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Installer reported error due to incompatibility of numpy and onnxruntime. I manually downgraded the versions but the installer keeps replacing old versions with the latest versions, which turned out to be incompatible. 

### Steps to reproduce the problem

Run the installer as instructed.

### Sysinfo

Windows 10, Python 3.11.9

### Relevant console log

```Shell
CUDA 12.4
Torch: 2.4.1+cu124
WARNING: Ignoring invalid distribution ~nnxruntime-gpu (D:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages)
Requirement already satisfied: onnxruntime-gpu in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (1.15.1)
Collecting onnxruntime-gpu
  Using cached onnxruntime_gpu-1.20.1-cp311-cp311-win_amd64.whl.metadata (4.7 kB)
Requirement already satisfied: coloredlogs in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from onnxruntime-gpu) (15.0.1)
Requirement already satisfied: flatbuffers in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from onnxruntime-gpu) (24.3.25)
Requirement already satisfied: numpy>=1.21.6 in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from onnxruntime-gpu) (1.25.2)
Requirement already satisfied: packaging in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from onnxruntime-gpu) (24.1)
Requirement already satisfied: protobuf in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from onnxruntime-gpu) (4.25.5)
Requirement already satisfied: sympy in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from onnxruntime-gpu) (1.13.3)
Requirement already satisfied: humanfriendly>=9.1 in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from coloredlogs->onnxruntime-gpu) (10.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from sympy->onnxruntime-gpu) (1.3.0)
Requirement already satisfied: pyreadline3 in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime-gpu) (3.5.4)
Using cached onnxruntime_gpu-1.20.1-cp311-cp311-win_amd64.whl (279.7 MB)
WARNING: Ignoring invalid distribution ~nnxruntime-gpu (D:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages)
Installing collected packages: onnxruntime-gpu
  Attempting uninstall: onnxruntime-gpu
    Found existing installation: onnxruntime-gpu 1.15.1
    Uninstalling onnxruntime-gpu-1.15.1:
      Successfully uninstalled onnxruntime-gpu-1.15.1
WARNING: Ignoring invalid distribution ~nnxruntime-gpu (D:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
inference-gpu 0.9.13 requires onnxruntime-gpu<=1.15.1, but you have onnxruntime-gpu 1.20.1 which is incompatible.
Successfully installed onnxruntime-gpu-1.20.1
Status: (onnx 1.17.0 (d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages), Requirement.parse('onnx==1.15.1'))
WARNING: Ignoring invalid distribution ~nnxruntime-gpu (D:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages)
ERROR: Could not find a version that satisfies the requirement onnx==1.15.1 (from versions: 0.1, 0.2, 0.2.1, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.13.0, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.16.0, 1.16.1, 1.16.2, 1.17.0)
ERROR: No matching distribution found for onnx==1.15.1
Ok
```

**Comment by XavierSX88** [comment]
I tried purging the cache, but it didn't help. Seems like the installer still tries to get the latest incompatible versions.

CUDA 12.4
Torch: 2.4.1+cu124
WARNING: Ignoring invalid distribution ~nnxruntime-gpu (D:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages)
Requirement already satisfied: onnxruntime-gpu in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (1.15.1)
Collecting onnxruntime-gpu
  Downloading onnxruntime_gpu-1.20.1-cp311-cp311-win_amd64.whl.metadata (4.7 kB)
Requirement already satisfied: coloredlogs in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from onnxruntime-gpu) (15.0.1)
Requirement already satisfied: flatbuffers in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from onnxruntime-gpu) (24.3.25)
Requirement already satisfied: numpy>=1.21.6 in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from onnxruntime-gpu) (1.25.2)
Requirement already satisfied: packaging in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from onnxruntime-gpu) (24.1)
Requirement already satisfied: protobuf in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from onnxruntime-gpu) (4.25.5)
Requirement already satisfied: sympy in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from onnxruntime-gpu) (1.13.3)
Requirement already satisfied: humanfriendly>=9.1 in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from coloredlogs->onnxruntime-gpu) (10.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from sympy->onnxruntime-gpu) (1.3.0)
Requirement already satisfied: pyreadline3 in d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime-gpu) (3.5.4)
Downloading onnxruntime_gpu-1.20.1-cp311-cp311-win_amd64.whl (279.7 MB)
   ---------------------------------------- 279.7/279.7 MB 8.0 MB/s eta 0:00:00
WARNING: Ignoring invalid distribution ~nnxruntime-gpu (D:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages)
Installing collected packages: onnxruntime-gpu
  Attempting uninstall: onnxruntime-gpu
    Found existing installation: onnxruntime-gpu 1.15.1
    Uninstalling onnxruntime-gpu-1.15.1:
      Successfully uninstalled onnxruntime-gpu-1.15.1
WARNING: Ignoring invalid distribution ~nnxruntime-gpu (D:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
inference-gpu 0.9.13 requires onnxruntime-gpu<=1.15.1, but you have onnxruntime-gpu 1.20.1 which is incompatible.
Successfully installed onnxruntime-gpu-1.20.1
Status: (onnx 1.17.0 (d:\swarmui\dlbackend\comfy\python_embeded\lib\site-packages), Requirement.parse('onnx==1.15.1'))
WARNING: Ignoring invalid distribution ~nnxruntime-gpu (D:\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages)
ERROR: Could not find a version that satisfies the requirement onnx==1.15.1 (from versions: 0.1, 0.2, 0.2.1, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.13.0, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.16.0, 1.16.1, 1.16.2, 1.17.0)
ERROR: No matching distribution found for onnx==1.15.1
Ok

**Comment by XavierSX88** [comment]
I think I found a way to go around it. 
change requirements.txt to 

albumentations>=1.4.16
insightface==0.7.3
onnx<=1.15.1
opencv-python>=4.7.0.72
numpy<=1.25.2
segment_anything
ultralytics


Edit the install.py Lin 76-83, replace all the version numbers to "1.15.1"

           if not is_installed(ort,"1.15.0",False):
                run_pip(ort,"--extra-index-url", "https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/")
        elif cuda_version is not None and float(cuda_version)>=12 and torch.torch_version.__version__ >= "2.4.0" : # CU12.x and latest torch
            print(f"Torch: {torch.torch_version.__version__}")
            if not is_installed(ort,"1.15.1",False): # latest ort-gpu
                run_pip(ort,"-U")
        elif not is_installed(ort,"1.15.1",False):
            run_pip(ort, "-U")
