### ISSUE TITLE
ReActor node in bypass mode outputs source image, not input image

### ISSUE THREAD

**Issue by lkarlslund** [Gourieff/comfyui-reactor-node#51]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

When using the node with ComfyUI and deactivating it with "bypass" (Ctrl-B), rather than outputting the input image, it outputs the source image, giving unpredictable results. 

It would make more sense that it outputs the unchanged input image. I'm not sure if this is a ReActor issue, or if deactivated nodes just output the first input image as the output. In that case switching the order of the input and source images on the node would probably fix the issue.

### Steps to reproduce the problem

Any workflow will show the issue, just bypass the node with Ctrl-B.

![image](https://github.com/Gourieff/comfyui-reactor-node/assets/8929787/e1e7082d-6088-4b0b-a306-a161fe3c30f8)

### Sysinfo

Windows, Python 3.10, ComfyUI standalone with venv

### Relevant console log

```Shell
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: Z:\ML\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
got prompt
WAS Node Suite: Batch 001 Index: 21
08:09:44 - ReActor Node - STATUS - Working: source face index [0], target face index [0]
08:09:48 - ReActor Node - STATUS - Target Face 0: Detected Gender -M-
08:09:48 - ReActor Node - STATUS - WRONG - Detected Gender doesn't match Condition
Prompt executed in 5.41 seconds
```

**Comment by Gourieff** [comment]
Hm 🤔 Ok, I will try your workflow
But what is the purpose of using it twice in a row? What's the scenario?

**Comment by Gourieff** [comment]
Fixed
