### ISSUE TITLE
Lots of people are having issues with reactor.

### ISSUE THREAD

**Issue by pennyvc** [Gourieff/comfyui-reactor-node#6]
I made a tutorial on Reactor and lots of people are having issue with the node, I suspect the install instructions are missing something.  I think something I did for another node made reactor work.

**Comment by Gourieff** [comment]
🤔
Can you provide your tutorial please?
I don't face any issues during installation within both ComfyUI portable and ComfyUI for A1111
I also tried a clean install, everything went fine

**Comment by Gourieff** [comment]
I think I know what the reason is
ControlNet got update and there's a dependence conflict with different versions of opencv
I've already fixed it in the SD WebUI ReActor today
So, will fix it here as well very soon

**Comment by Gourieff** [comment]
Node is updated, try it

Also I recommend to use [ComfyUI Manager](https://github.com/ltdrdata/ComfyUI-Manager) to update all dependencies in a correct way, and this is a very simple way to install other nodes

**Comment by pennyvc** [comment]
All good, https://www.youtube.com/watch?v=FShlpMxbU0E  mines just a how to use tutorial and lots of people were commenting that it was broken. and id had some issues (mines not a portable install but while fixing something else, it fixed reactor so I couldn't easily track down the issue)

**Comment by TilBill** [comment]
Hi I have Problems with the note during install

![grafik](https://github.com/Gourieff/comfyui-reactor-node/assets/115370406/88d0e0ab-9078-4381-a02d-90e48186867a)
