### ISSUE TITLE
Gender handling in ReActor

### ISSUE THREAD

**Issue by wknudsen** [Gourieff/comfyui-reactor-node#7]
Suggestion: The gender handling you added in the SD extension is amazing. Any chance of it being added to the ComfyUI node?

**Comment by Gourieff** [comment]
Yes, it can be done, I'm going to implement this function next week

**Comment by Gourieff** [comment]
Done!

**Comment by wknudsen** [comment]
That's very nice, thank you so much. I have updated the node and tested it, and it worked as expected.

I initially had a problem: After git pull updating, the node (in an existing workflow) had the new gender fields, but the two inputs kept their original legends but had their new positions which caused my wiring to fail. It was very confusing and I didn't understand it until I deleted the node and replaced it with a new one.

The new nomenclature - source for the source faces and input for the image to be changed - is very confusing, at least to me. Source and input are two concepts rather close to each other. Much better to call them what you do in A1111: Source for the source faces, target for the image that is to be changed. You actually do that in the ComfyUI log.

If you don't know ReActor from A1111, it's not clear that you can specify a list of indexes, not just one index.

A question: Do you count the detected faces from left to right, or is top to bottom also involved?

A wish: Do you have (or know of) a way of showing the analysis of an image: The number of faces found and a sequence of gender M and F's? If the information is readily available, you could output the information as text or - ideally - the original target image with face number and gender marked on top of its detected faces. This would be nice for A1111 too. Not everyone has access to logs so some output would be preferable, although log output could be a first step.
