### ISSUE TITLE
inswapper_128.onnx may be unsafe

### ISSUE THREAD

**Issue by chrisbward** [Gourieff/comfyui-reactor-node#71]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Hi, please read the following for your consideration;
https://github.com/deepinsight/insightface/issues/2315

It's important for the community as a whole to not get in to the habit of downloading unknown binaries. I tried my best to get the authors of inswapper_128.onnx to publish the checksum hash of the file, but to no joy. 

Proceed with caution.

p.s. runew0lf, you are the lamest

### Steps to reproduce the problem

Your workflow
n/a

### Sysinfo

n/a

### Relevant console log

```Shell
n/a
```

**Comment by Gourieff** [comment]
Answered here https://github.com/Gourieff/sd-webui-reactor/discussions/133#discussioncomment-7300177
