### ISSUE TITLE
Reactor closes me comfyui

### ISSUE THREAD

**Issue by laureartwork** [Gourieff/comfyui-reactor-node#75]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I have everything installed and I have no problem launching images, all the nodes are up to date.
I did several reboots to make sure I didn't forget anything. But in classic I have no problem and I can calculate images.
But when I switch to On with reactor ConfyUI closes. 
I used roop before and had no problem outputting images. Does this use the same type of parameter? I'm thinking of redoing a complete installation but first I prefer to share my problem and see if there isn't a simple solution.

Reactor Node - STATUS - Working: source face index [0], target face [0]
Reactor Node - STATUS - Analyzing Source Image...

E:\ComfyUI>pause
Press any key to continue...

### Steps to reproduce the problem

Your workflow

### Sysinfo

Windows and nvidia 3070
ComfyUI portable

### Relevant console log

```Shell
08:16:57 - ReActor Node - STATUS - Working: source face index [0], target face index [0]
08:16:57 - ReActor Node - STATUS - Analyzing Source Image...

E:\ComfyUI>pause
Press any key to continue...
```

### Additional information

[_No response_](https://github.com/Gourieff/comfyui-reactor-node/discussions/73#discussion-5749958)
I have exactly the same problem but everything is up to date. And I have an Nvidia

**Comment by Gourieff** [comment]
Try the following https://github.com/Gourieff/comfyui-reactor-node/discussions/73#discussioncomment-7317684

**Comment by TilBill** [comment]
Hi same issu today it just stop working!!
I reinsall everything but doesnt work. I did follow your #73comment no fix ;(

"15:48:42 - ReActor Node - STATUS - Working: source face index [0], target face index [0]
15:48:42 - ReActor Node - STATUS - Analyzing Source Image...

C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable>pause
Drücken Sie eine beliebige Taste . . ."

after that show's up in consol comfyui shut down

**Comment by Gourieff** [comment]
This can also happen if you run out of RAM
