### ISSUE TITLE
slow_conv2d_forward_mps: input(device='cpu') and weight(device=mps:0')  must be on the same device

### ISSUE THREAD

**Issue by alessandroperilli** [Gourieff/comfyui-reactor-node#77]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I am on macOS, and the ReActor node works fine as long as I don't use CodeFormer or another face restoring model.

If I do, the node raises the following error:

`RuntimeError: slow_conv2d_forward_mps: input(device='cpu') and weight(device=mps:0')  must be on the same device`

### Steps to reproduce the problem

<img width="332" alt="Screenshot 2023-10-19 at 18 20 25" src="https://github.com/Gourieff/comfyui-reactor-node/assets/9775949/fe45d394-ccb3-4aa6-8204-54100a377535">

### Sysinfo

M2

### Relevant console log

```Shell
no need
```

### Additional information

This issue can be solved by patching the `retinaface.py` file in the Facelib instance that comes with this node, as described `here`.

To test the workaround, I changed the following line in retinaface.py:

`device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')`

with

`device = torch.device('cuda' if torch.cuda.is_available() else 'mps')`

and the node now works with Codeformer, too.

It's not the correct implementation, but it's a temporary fix until this gets fixed.

**Comment by Gourieff** [comment]
Hmm... Ok, I will take a look

**Comment by alessandroperilli** [comment]
Sorry, I realised that my link to the word "here" is not there. 

This is the fix for this bug as implemented in the ReActor node: 
[https://github.com/Gourieff/comfyui-reactor-node/commit/a35c0258e63a887faddf572d95ad51cc91a8c8c8](https://github.com/Gourieff/comfyui-reactor-node/commit/a35c0258e63a887faddf572d95ad51cc91a8c8c8)

I used the same approach with your node for both `retinaface.py` and `face_detectory.py`
