### ISSUE TITLE
[Feature]: Image sequence or Video

### ISSUE THREAD

**Issue by LubuLubu2** [Gourieff/comfyui-reactor-node#79]
### Feature description

First of all, Thank you, amazing addon,

It would be great if we can select a folder (Image Sequence) and it automatically swap each photo or a Video input.

Right now i'm using photoshop to create Image Sqquence of a clip i like (5second of a 30fps video = 150 images) then i swap faces one by one manualy, it would be awesome if it does that automatically or it takes the video directly and star the swaping progress.

**Comment by Gourieff** [comment]
Hi :)
But this is already implemented in ComfyUI
![изображение](https://github.com/Gourieff/comfyui-reactor-node/assets/85128026/241e14bf-eaf8-4587-8e30-b83be40f28cd)

**Comment by Gourieff** [comment]
You can even save it to a video file with AnimateDiff

![изображение](https://github.com/Gourieff/comfyui-reactor-node/assets/85128026/f882a6de-1e79-48df-bfaa-9bed55c25d08)

**Comment by LubuLubu2** [comment]
wow nice nice nice. Thank you very very much. haven't used AnimateDiff because i feared that it wont work on my 4GB card. i will try it today, Thank alot.

**Comment by LubuLubu2** [comment]
Tried it and it Worked. Thank you so much,
It's fast, no need high spec PC, created a 5sec (24fps) clip in less than 10min even with face restore GFPGAN1.4.
Sadly can't use "Animatediffcombine" to create MP4 videos because of "ffmpeg" not found error which is no important cause having all the frames as image is better for later editing, it can combine it to webm and gif tho.

Amazing work, Thank you again.
