### ISSUE TITLE
[SOLVED] Missing Swap Model

### ISSUE THREAD

**Issue by 631557fcd** [Gourieff/comfyui-reactor-node#82]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Reactor Node on Ubuntu, using shared venv with automatic1111 throws following error: 

Prompt outputs failed validation ReActorFaceSwap: - Value not in list: swap_model: 'None' not in []

The swap_model field in the node shows: null

It seems to be a small issue, that could be solved if i sylink the file needed. Which model (swap_model) do i have to put in which folder? Thanks in advance!

### Steps to reproduce the problem

Installed via Manager

### Sysinfo

Ubuntu, Venv shared with Automatic1111

### Relevant console log

```Shell
ERROR:root:Failed to validate prompt for output 17:
ERROR:root:* ReActorFaceSwap 1:
ERROR:root:  - Required input is missing: swap_model
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 4:
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
```

**Comment by CyborgYL** [comment]
same issue here. I installed this via ComfyUI manager menu

**Comment by jmkl** [comment]
you need inswapper model. the one that mention here https://github.com/Gourieff/comfyui-reactor-node#ii-attributeerror-nonetype-object-has-no-attribute-get

**Comment by 631557fcd** [comment]
Thanks, that fixed this issue. Created the directory  ComfyUI\models\insightface and symlinked to inswapper_128.onnx in my existing automatic1111 installation.
