### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by TilBill** [Gourieff/comfyui-reactor-node#9]
have problems with the node install

 × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

tryed than the troubleshoot and get more issues 

Microsoft Windows [Version 10.0.19045.3324]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable>python_embeded\python.exe -m pip install -U pip
Requirement already satisfied: pip in c:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (23.2.1)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable>python_embeded\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl
WARNING: Requirement 'insightface-0.7.3-cp310-cp310-win_amd64.whl' looks like a filename, but the file does not exist
Processing c:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\insightface-0.7.3-cp310-cp310-win_amd64.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\insightface-0.7.3-cp310-cp310-win_amd64.whl'

C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable>

**Comment by jiangli0925** [comment]
**fatal error C1083: 无法打开包括文件: “Python.h”: No such file or directory**
      running build_ext
      building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\insightface
      creating build\temp.win-amd64-cpython-310\Release\insightface\thirdparty
      creating build\temp.win-amd64-cpython-310\Release\insightface\thirdparty\face3d
      creating build\temp.win-amd64-cpython-310\Release\insightface\thirdparty\face3d\mesh
      creating build\temp.win-amd64-cpython-310\Release\insightface\thirdparty\face3d\mesh\cython
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iinsightface/thirdparty/face3d/mesh/cython -IE:\sd\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\numpy\core\include -IE:\sd\comfyui\ComfyUI_windows_portable\python_embeded\include -IE:\sd\comfyui\ComfyUI_windows_portable\python_embeded\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpinsightface/thirdparty/face3d/mesh/cython/mesh_core.cpp /Fobuild\temp.win-amd64-cpython-310\Release\insightface/thirdparty/face3d/mesh/cython/mesh_core.obj
      mesh_core.cpp
      insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(147): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
      insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(147): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
      insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(210): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
      insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(210): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
      insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(294): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
      insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(294): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iinsightface/thirdparty/face3d/mesh/cython -IE:\sd\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\numpy\core\include -IE:\sd\comfyui\ComfyUI_windows_portable\python_embeded\include -IE:\sd\comfyui\ComfyUI_windows_portable\python_embeded\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpinsightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpp /Fobuild\temp.win-amd64-cpython-310\Release\insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.obj
      mesh_core_cython.cpp
      insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpp(36): fatal error C1083: 无法打开包括文件: “Python.h”: No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects
PS E:\sd\comfyui\ComfyUI_windows_portable>

**Comment by Gourieff** [comment]
Please read [troubleshooting](https://github.com/Gourieff/comfyui-reactor-node#troubleshooting)

**Comment by Gourieff** [comment]
Just try 

      python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl

if you downloaded `insightface-0.7.3-cp311-cp311-win_amd64.whl`

**Comment by RedReindeer** [comment]
https://raw.githubusercontent.com/Gourieff/Assets/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl.
Hey is this link working. I cant reach this page getting an error. 
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/150056778/9ac85344-74df-40a5-9cbc-c70b9dc506ea)

**Comment by JustinDEvasia116** [comment]
> Just try
> 
> ```
>   python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl
> ```
> 
> if you downloaded `insightface-0.7.3-cp311-cp311-win_amd64.whl`

But the link is Broken, couldn't able to download it
