### ISSUE TITLE
[Feature]:  Parameter for how much of face to select - padding, feather or something

### ISSUE THREAD

**Issue by EricRollei** [Gourieff/comfyui-reactor-node#93]
### Feature description

I have been using the Reactor fast face swap node with the inswapper_128.onnx  (it's the only one that works for me)
In some renders I only want to change the face, not the hair or hat, but the selection area is often too big or is feathered very much so the hair or hat is partly changed.  It looks awful to have it switched half way.   Maybe there's a setting that a user could use to control how big the selection is? Or to limit it to just the face and not forehead or hair?   
Yolo5l seems to select less area, but still an issue.

**Comment by EricRollei** [comment]
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/97568200/4678da46-b1d9-4477-a67a-1604961adbde)

Here you can see using inswapper and Yolo5l  even parts above her forehead have been corrupted.

**Comment by Gourieff** [comment]
You can use masks in ComfyUI https://github.com/Gourieff/comfyui-reactor-node/discussions/72#discussioncomment-7342785 with such nodes like ImpactPack collection or Masquerade
Here's some examples of how it looks like when swapping with mask https://github.com/Gourieff/sd-webui-reactor/discussions/124#discussioncomment-7342328

**Comment by EricRollei** [comment]
I looked at the linked comment and post, but I didn't totally understand you.  Are you saying I should use something in addition to the reactor node or did you mean skip the reactor node and use the other tools?    It would be very cool to have the option to take the reactor face data and upscale or apply another mask to it before it's pasted.  In that case all you'd need to do is make the face data and the mask as output widgets I think?

**Comment by Gourieff** [comment]
In additional of course
No need to reinvent the wheel if it already exists, just use it
There are a lot of different wonderful nodes that can be used in one specific workflow according to the task you have
UltralyticsDetectorProvider, BboxDetectorSEGS, SAMLoader, SAMDetectorSegmented, Mask Morphology, Blur, Cut by Mask, Past by Mask...
You can read here about how to use some of them https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/detectors.md
All these nodes can be used together for the mask auto-detection of the input image and combining with the swapped image by the mask
You can google for existing workflows with the mask auto-detection
If you don't need any auto-detection, you can set the mask manually - just right-click on the load image node (for the face source image) and click 'Open in Mask Editor'
YouTube is full of tutorials on this topic, learn it to improve your skill 

I don't want to bring all the existing functions and options from other nodes to my node. Why? I don't want to make ReActor node heavy and complicated to use especially when there are a great number of other nodes for different tasks

**Comment by EricRollei** [comment]
Hmm...  I understand what you wrote. and I already do use Data's face restore in other parts of my workflow.  I'm mostly concerned about the areas outside the face that reactor messes up because those areas are harder to fix.    So if you understood me, then I think you are suggesting taking a copy of the image prior to the Reactor face swap and then masking everything but the center part of the face and pasting that back over after the reactor node,  to cover up the portions outside of the face that the reactor node messes up?    I just think all of that would be easier with the mask and face data that the Reactor node used or even having the option to take the face data as an output prior to pasting so it could be trimmed and upscaled prior to pasting.   Thank you for what you've already made so far.

**Comment by Gourieff** [comment]
That's what I'm trying to say :)
This part of image won't be messed if you will add a mask detection pipeline in your workflow
The pipeline with such an amazing nodes as I mentioned above (by ImpactPack and Masquerade)
A face will be swapped without affecting other details of your image
