### ISSUE TITLE
Node nowhere to be found in the UI -> Add Node / Search

### ISSUE THREAD

**Issue by cubicalia** [Gourieff/comfyui-reactor-node#95]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

After installing the node through the Manager and restarting ComfyUI, I don't seem to see the node anywhere in the UI, it won't even show on the search menu.

### Steps to reproduce the problem

Your workflow
- I've installed the node through the manager.
- Restarted ComfyUI
- Bug persisted
- Fetched all updates for ComfyUI
- Uninstalled the ReFactor Custom Node
- Restarted ComfyUI
- Reinstalled the ReFactor
- Restarted ComfyUI
- Still the node not showing

### Sysinfo

- Windows 11
- NVidia RTX 4090 with latest studio driver

### Relevant console log

```Shell
Not sure
```

**Comment by Spearin** [comment]
I have the same issue.

**Comment by Gourieff** [comment]
Probably your OS environment is not able to build Insightface during the installation process
Try https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

**Comment by Gourieff** [comment]
Or maybe you have another error
To detect it right - show please your console log

**Comment by crimpproduction** [comment]
happens to me too on windows.. i've tried the manual insightfacebuild until the `python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl` but then it says 

> ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\AI STABLE DIFFUSION\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\cv2\\cv2.pyd' Consider using the `--user` option or check the permissions.

so i use the `--user` like this in the cmd: `python_embeded\python.exe -m pip install --user insightface-0.7.3-cp311-cp311-win_amd64.whl` until it says successful, but still the reactor node doesn't show up when I search it

**Comment by hamster-poodle** [comment]
I could use reActor in the webUI, but not in ComfyUI. I am in the same situation as [crimpproduction].

**Comment by sh0ber** [comment]
I do have the InsightFace folder in python_embeded (installed via .whl), restarted, still no node for ReActor

**Comment by gxbsyxh** [comment]
about, (IMPORT FAILED): D:\ComfyUI_windows_portable\ comfyui \custom_nodes\comfyui-reactor-node
After half a month, I finally found the problem and made a record for my later friends.
opencv-python==4.7.0 version too new will cause (IMPORT FAILED)
Use the following cmd command to uninstall the original version and install the older version
Under the cmd command D:\ComfyUI_windows_portable22\python_embeded enter:
python.exe -m pip uninstall opencv-python
Reinstall the old version
python.exe -m pip install opencv-python==4.7.0.68
Below are the version numbers I looked up, which may need to be tried one by one
opencv-python==4.7.0 (from versions: 3.4.0.14, 3.4.10.37 3.4.11.41, 3.4.11.43 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38 4.4.0.40, 4.4.0.42 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66 4.7.0.68, 4.7.0.72 4.8.0.74, 4.8.0.76 4.8.1.78)

**Comment by m7rick** [comment]
Modify this part in install.py:
def run_pip(*args):
    subprocess.run([sys.executable, "-m", "pip","--user", "install", "--no-warn-script-location", *args])
